/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_BOOK_DETAILE_H__660DBB6F_4F80_48D7_91E0_1BB957421A4E
#define __WIN_BOOK_DETAILE_H__660DBB6F_4F80_48D7_91E0_1BB957421A4E


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER g_win_book_detail;
extern CONTAINER Containerbook_2;
extern TEXT_FIELD TextFieldbook_3;
extern TEXT_FIELD TextFieldbook_2;
extern CONTAINER Containerbook_1;
extern TEXT_FIELD TextFieldBOOK_1;

//g_win_book_detail ------------------------------------------------------------------------
static VACTION book_detailkeymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT book_detailcallback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_book_detail = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {40, 20, 640, 478},
		.style = {
			.bShowIdx = WSTL_EMIAL_OL_CON, .bHLIdx = WSTL_EMIAL_OL_CON, .bSelIdx = WSTL_EMIAL_OL_CON, .bGrayIdx = WSTL_EMIAL_OL_CON
		},
		.pfnKeyMap = book_detailkeymap, .pfnCallback = book_detailcallback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&TextFieldBOOK_1,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//TextFieldBOOK_1 ------------------------------------------------------------------------

TEXT_FIELD TextFieldBOOK_1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {82, 25, 104, 21},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&Containerbook_1, .pRoot = (POBJECT_HEAD)&g_win_book_detail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CTI_PROG_BRIEF,
	.pString = NULL
};

//Containerbook_1 ------------------------------------------------------------------------

CONTAINER Containerbook_1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {231, 400, 112, 33},
		.style = {
			.bShowIdx = WSTL_BULE_ITEM, .bHLIdx = WSTL_BULE_ITEM, .bSelIdx = WSTL_BULE_ITEM, .bGrayIdx = WSTL_BULE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&TextFieldbook_3, .pRoot = (POBJECT_HEAD)&g_win_book_detail
	},
	.pNextInCntn = (POBJECT_HEAD)&TextFieldbook_2,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//TextFieldbook_2 ------------------------------------------------------------------------

TEXT_FIELD TextFieldbook_2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {251, 405, 60, 22},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&Containerbook_1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//TextFieldbook_3 ------------------------------------------------------------------------

TEXT_FIELD TextFieldbook_3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {343, 400, 66, 33},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&Containerbook_2, .pRoot = (POBJECT_HEAD)&g_win_book_detail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};

//Containerbook_2 ------------------------------------------------------------------------

CONTAINER Containerbook_2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {111, 86, 497, 243},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_book_detail
	},
	.pNextInCntn = (POBJECT_HEAD)NULL,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};
#endif//__WIN_BOOK_DETAILE_H__660DBB6F_4F80_48D7_91E0_1BB957421A4E

