/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_CHILD_LOCK_LIST_VEGA_H__70ADB0F6_8019_4A69_906A_638BEA5AE940
#define __WIN_CHILD_LOCK_LIST_VEGA_H__70ADB0F6_8019_4A69_906A_638BEA5AE940


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER childlock_list_item6;
extern BITMAP childlock_list_flag2;
extern TEXT_FIELD childlock_list_modify;
extern BITMAP childlock_list_flag3;
extern CONTAINER childlock_list_item5;
extern TEXT_FIELD childlock_list_name5;
extern BITMAP childlock_list_flag8;
extern TEXT_FIELD childlock_list_name6;
extern TEXT_FIELD childlock_list_back;
extern TEXT_FIELD childlock_list_idx1;
extern OBJLIST childlock_list_ol;
extern CONTAINER childlock_list_item2;
extern TEXT_FIELD childlock_list_name3;
extern TEXT_FIELD childlock_list_idx6;
extern CONTAINER g_win_childlock_list;
extern CONTAINER childlock_list_item3;
extern SCROLL_BAR childlock_list_scb;
extern CONTAINER childlock_list_item4;
extern TEXT_FIELD childlock_list_idx2;
extern TEXT_FIELD childlock_list_idx4;
extern TEXT_FIELD childlock_list_name9;
extern TEXT_FIELD childlock_list_name8;
extern TEXT_FIELD childlock_list_idx3;
extern TEXT_FIELD childlock_list_title_name;
extern CONTAINER childlock_list_item8;
extern TEXT_FIELD childlock_list_idx9;
extern TEXT_FIELD childlock_list_exit;
extern TEXT_FIELD childlock_list_comfire;
extern CONTAINER childlock_list_action;
extern TEXT_FIELD childlock_list_idx7;
extern CONTAINER childlock_list_con;
extern BITMAP childlock_list_flag9;
extern CONTAINER childlock_list_item9;
extern TEXT_FIELD childlock_list_idx5;
extern TEXT_FIELD childlock_list_name10;
extern TEXT_FIELD childlock_list_idx10;
extern BITMAP childlock_list_flag7;
extern BITMAP childlock_list_flag10;
extern TEXT_FIELD childlock_list_name2;
extern CONTAINER childlock_list_item10;
extern TEXT_FIELD childlock_list_name7;
extern BITMAP childlock_list_flag5;
extern CONTAINER childlock_list_item7;
extern TEXT_FIELD childlock_list_name4;
extern CONTAINER childlock_list_item1;
extern TEXT_FIELD childlock_list_name1;
extern BITMAP childlock_list_flag1;
extern BITMAP childlock_list_flag6;
extern TEXT_FIELD childlock_list_idx8;
extern BITMAP childlock_list_flag4;

//g_win_childlock_list ------------------------------------------------------------------------
static VACTION childlock_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT childlock_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_childlock_list = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 720, 576},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = childlock_list_keymap, .pfnCallback = childlock_list_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//childlock_list_con ------------------------------------------------------------------------

CONTAINER childlock_list_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {278, 56, 402, 435},
		.style = {
			.bShowIdx = WSTL_RCI_COM_MENU_BG, .bHLIdx = WSTL_RCI_COM_MENU_BG, .bSelIdx = WSTL_RCI_COM_MENU_BG, .bGrayIdx = WSTL_RCI_COM_MENU_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_childlock_list
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_ol,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//childlock_list_ol ------------------------------------------------------------------------
static VACTION childlock_list_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT childlock_list_item_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD childlock_list_ol_ListField[] = {
	(POBJECT_HEAD)&childlock_list_item1,
	(POBJECT_HEAD)&childlock_list_item2,
	(POBJECT_HEAD)&childlock_list_item3,
	(POBJECT_HEAD)&childlock_list_item4,
	(POBJECT_HEAD)&childlock_list_item5,
	(POBJECT_HEAD)&childlock_list_item6,
	(POBJECT_HEAD)&childlock_list_item7,
	(POBJECT_HEAD)&childlock_list_item8,
	(POBJECT_HEAD)&childlock_list_item9,
	(POBJECT_HEAD)&childlock_list_item10,
};
OBJLIST childlock_list_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {292, 92, 371, 344},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_RCI_C_GRAY, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = childlock_list_item_keymap, .pfnCallback = childlock_list_item_callback,
		.pNext = (POBJECT_HEAD)&childlock_list_action, .pRoot = (POBJECT_HEAD)&childlock_list_con
	},
	.pListField = childlock_list_ol_ListField,
	.scrollBar = &childlock_list_scb,
	.bListStyle = LIST_VER | LIST_SINGLE_SLECT | LIST_ITEMS_NOCOMPLETE | LIST_SCROLL | LIST_GRID | LIST_FOCUS_FIRST | LIST_PAGE_KEEP_CURITEM | LIST_FULL_PAGE,
	.wDep = 10, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//childlock_list_item1 ------------------------------------------------------------------------

CONTAINER childlock_list_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 10, .bDownID = 2,
		.frame = {290, 96, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item2, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx1 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 97, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name1, .pRoot = (POBJECT_HEAD)&childlock_list_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0] 
};

//childlock_list_name1 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 97, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag1, .pRoot = (POBJECT_HEAD)&childlock_list_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10] 
};

//childlock_list_flag1 ------------------------------------------------------------------------

BITMAP childlock_list_flag1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 97, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item2 ------------------------------------------------------------------------

CONTAINER childlock_list_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {290, 130, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item3, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx2 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 130, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name2, .pRoot = (POBJECT_HEAD)&childlock_list_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1] 
};

//childlock_list_name2 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 130, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag2, .pRoot = (POBJECT_HEAD)&childlock_list_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11] 
};

//childlock_list_flag2 ------------------------------------------------------------------------

BITMAP childlock_list_flag2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 130, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item3 ------------------------------------------------------------------------

CONTAINER childlock_list_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {290, 164, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item4, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx3 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 164, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name3, .pRoot = (POBJECT_HEAD)&childlock_list_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2] 
};

//childlock_list_name3 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 164, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag3, .pRoot = (POBJECT_HEAD)&childlock_list_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12] 
};

//childlock_list_flag3 ------------------------------------------------------------------------

BITMAP childlock_list_flag3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 164, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item4 ------------------------------------------------------------------------

CONTAINER childlock_list_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {289, 198, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item5, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx4 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 198, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name4, .pRoot = (POBJECT_HEAD)&childlock_list_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3] 
};

//childlock_list_name4 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 198, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag4, .pRoot = (POBJECT_HEAD)&childlock_list_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13] 
};

//childlock_list_flag4 ------------------------------------------------------------------------

BITMAP childlock_list_flag4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 198, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item5 ------------------------------------------------------------------------

CONTAINER childlock_list_item5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {289, 232, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item6, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx5,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx5 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 232, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name5, .pRoot = (POBJECT_HEAD)&childlock_list_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4] 
};

//childlock_list_name5 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 232, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag5, .pRoot = (POBJECT_HEAD)&childlock_list_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14] 
};

//childlock_list_flag5 ------------------------------------------------------------------------

BITMAP childlock_list_flag5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 232, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item6 ------------------------------------------------------------------------

CONTAINER childlock_list_item6 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 7,
		.frame = {289, 266, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item7, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx6,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx6 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 266, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name6, .pRoot = (POBJECT_HEAD)&childlock_list_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5] 
};

//childlock_list_name6 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 266, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag6, .pRoot = (POBJECT_HEAD)&childlock_list_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15] 
};

//childlock_list_flag6 ------------------------------------------------------------------------

BITMAP childlock_list_flag6 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 266, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item7 ------------------------------------------------------------------------

CONTAINER childlock_list_item7 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 7, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 8,
		.frame = {290, 300, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item8, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx7,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx7 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 300, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name7, .pRoot = (POBJECT_HEAD)&childlock_list_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6] 
};

//childlock_list_name7 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 300, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag7, .pRoot = (POBJECT_HEAD)&childlock_list_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16] 
};

//childlock_list_flag7 ------------------------------------------------------------------------

BITMAP childlock_list_flag7 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 300, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item8 ------------------------------------------------------------------------

CONTAINER childlock_list_item8 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 8, .bLeftID = 0, .bRightID = 0, .bUpID = 7, .bDownID = 9,
		.frame = {289, 334, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item9, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx8,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx8 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 334, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name8, .pRoot = (POBJECT_HEAD)&childlock_list_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7] 
};

//childlock_list_name8 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 334, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag8, .pRoot = (POBJECT_HEAD)&childlock_list_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17] 
};

//childlock_list_flag8 ------------------------------------------------------------------------

BITMAP childlock_list_flag8 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 334, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item9 ------------------------------------------------------------------------

CONTAINER childlock_list_item9 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 9, .bLeftID = 0, .bRightID = 0, .bUpID = 8, .bDownID = 10,
		.frame = {289, 368, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_item10, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx9,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx9 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx9 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 368, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name9, .pRoot = (POBJECT_HEAD)&childlock_list_item9
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8] 
};

//childlock_list_name9 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name9 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 368, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag9, .pRoot = (POBJECT_HEAD)&childlock_list_item9
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[18] 
};

//childlock_list_flag9 ------------------------------------------------------------------------

BITMAP childlock_list_flag9 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 368, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item9
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_item10 ------------------------------------------------------------------------

CONTAINER childlock_list_item10 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 10, .bLeftID = 0, .bRightID = 0, .bUpID = 9, .bDownID = 1,
		.frame = {289, 402, 362, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_scb, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_idx10,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//childlock_list_idx10 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_idx10 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 402, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_name10, .pRoot = (POBJECT_HEAD)&childlock_list_item10
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9] 
};

//childlock_list_name10 ------------------------------------------------------------------------

TEXT_FIELD childlock_list_name10 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 402, 260, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_flag10, .pRoot = (POBJECT_HEAD)&childlock_list_item10
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[19] 
};

//childlock_list_flag10 ------------------------------------------------------------------------

BITMAP childlock_list_flag10 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {611, 402, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_item10
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//childlock_list_scb ------------------------------------------------------------------------

SCROLL_BAR childlock_list_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {653, 98, 12, 330},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_ol
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 10,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 280},
	.nMax = 100, .nPos = 1
};

//childlock_list_action ------------------------------------------------------------------------

CONTAINER childlock_list_action = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {278, 450, 402, 64},
		.style = {
			.bShowIdx = WSTL_RCI_LAST_WIN_BG_NOTOP, .bHLIdx = WSTL_RCI_LAST_WIN_BG, .bSelIdx = WSTL_RCI_LAST_WIN_BG, .bGrayIdx = WSTL_RCI_LAST_WIN_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_title_name, .pRoot = (POBJECT_HEAD)&childlock_list_con
	},
	.pNextInCntn = (POBJECT_HEAD)&childlock_list_comfire,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//childlock_list_comfire ------------------------------------------------------------------------

TEXT_FIELD childlock_list_comfire = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {292, 463, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_YELLOW_ITEM, .bHLIdx = WSTL_RCI_YELLOW_ITEM, .bSelIdx = WSTL_RCI_YELLOW_ITEM, .bGrayIdx = WSTL_RCI_YELLOW_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_modify, .pRoot = (POBJECT_HEAD)&childlock_list_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_BUTTON_CONFIRM,
	.pString = NULL
};

//childlock_list_modify ------------------------------------------------------------------------

TEXT_FIELD childlock_list_modify = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {380, 463, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_exit, .pRoot = (POBJECT_HEAD)&childlock_list_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_CHANGE,
	.pString = NULL
};

//childlock_list_exit ------------------------------------------------------------------------

TEXT_FIELD childlock_list_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {468, 463, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_BLUE_ITEM, .bHLIdx = WSTL_RCI_BLUE_ITEM, .bSelIdx = WSTL_RCI_BLUE_ITEM, .bGrayIdx = WSTL_RCI_BLUE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&childlock_list_back, .pRoot = (POBJECT_HEAD)&childlock_list_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//childlock_list_back ------------------------------------------------------------------------

TEXT_FIELD childlock_list_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {555, 464, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};

//childlock_list_title_name ------------------------------------------------------------------------

TEXT_FIELD childlock_list_title_name = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {304, 60, 150, 30},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&childlock_list_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = NULL
};
#endif//__WIN_CHILD_LOCK_LIST_VEGA_H__70ADB0F6_8019_4A69_906A_638BEA5AE940
