/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_MANUAL_UPDATE_VEGA_H__6D81EB07_2FA2_4CCB_B6BE_ACC40C91D26B
#define __WIN_MANUAL_UPDATE_VEGA_H__6D81EB07_2FA2_4CCB_B6BE_ACC40C91D26B


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD txt_mu_item_name1;
extern EDIT_FIELD txt_mu_item_value2;
extern CONTAINER g_win_manual_update;
extern TEXT_FIELD manual_update_title;
extern TEXT_FIELD manual_update_back;
extern TEXT_FIELD manual_update_comfire;
extern CONTAINER manual_update_con;
extern TEXT_FIELD txt_mu_item_name2;
extern CONTAINER manual_update_con_item2;
extern TEXT_FIELD manual_update_modify;
extern CONTAINER manual_update_help;
extern EDIT_FIELD txt_mu_item_value4;
extern EDIT_FIELD txt_mu_item_value1;
extern CONTAINER manual_update_con_item4;
extern CONTAINER manual_update_con_item1;
extern TEXT_FIELD txt_mu_item_name4;
extern CONTAINER manual_update_con_item3;
extern TEXT_FIELD manual_update_exit;
extern MULTISEL txt_mu_item_value3;
extern TEXT_FIELD txt_mu_item_name3;

//g_win_manual_update ------------------------------------------------------------------------
static VACTION win_common_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_main_freq_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_manual_update = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 720, 576},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = win_common_item_keymap, .pfnCallback = win_main_freq_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&manual_update_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//manual_update_con ------------------------------------------------------------------------
static VACTION con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER manual_update_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {286, 110, 384, 300},
		.style = {
			.bShowIdx = WSTL_RCI_COM_MENU_BG, .bHLIdx = WSTL_RCI_COM_MENU_BG, .bSelIdx = WSTL_RCI_COM_MENU_BG, .bGrayIdx = WSTL_RCI_COM_MENU_BG
		},
		.pfnKeyMap = con_keymap, .pfnCallback = con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_manual_update
	},
	.pNextInCntn = (POBJECT_HEAD)&manual_update_title,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//manual_update_title ------------------------------------------------------------------------

TEXT_FIELD manual_update_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {328, 115, 119, 24},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_con_item1, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_MANUAL_UPDATE,
	.pString = NULL
};

//manual_update_con_item1 ------------------------------------------------------------------------

CONTAINER manual_update_con_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 2,
		.frame = {295, 169, 345, 30},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_con_item2, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mu_item_name1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mu_item_name1 ------------------------------------------------------------------------

TEXT_FIELD txt_mu_item_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 166, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mu_item_value1, .pRoot = (POBJECT_HEAD)&manual_update_con_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY,
	.pString = NULL
};

//txt_mu_item_value1 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mu_item_value1_pattern[] = "f32";
static const UINT8 txt_mu_item_value1_Suffix[] = {0, 77, 0, 72, 0, 122, 0, 0}; //Suffix = MHz
EDIT_FIELD txt_mu_item_value1 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {468, 166, 155, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_con_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mu_item_value1_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[20],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mu_item_value1_Suffix,
	.valbak = 0
};

//manual_update_con_item2 ------------------------------------------------------------------------

CONTAINER manual_update_con_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {295, 211, 342, 30},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_con_item3, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mu_item_name2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mu_item_name2 ------------------------------------------------------------------------

TEXT_FIELD txt_mu_item_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 211, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mu_item_value2, .pRoot = (POBJECT_HEAD)&manual_update_con_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SEARCH_COD_SYMBOL,
	.pString = NULL
};

//txt_mu_item_value2 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mu_item_value2_pattern[] = "s5";
static const UINT8 txt_mu_item_value2_Suffix[] = {0, 75, 0, 66, 0, 97, 0, 117, 0, 100, 0, 0}; //Suffix = KBaud
EDIT_FIELD txt_mu_item_value2 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {468, 211, 154, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_con_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mu_item_value2_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[21],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mu_item_value2_Suffix,
	.valbak = 0
};

//manual_update_con_item3 ------------------------------------------------------------------------

CONTAINER manual_update_con_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {295, 255, 345, 30},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_con_item4, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mu_item_name3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mu_item_name3 ------------------------------------------------------------------------

TEXT_FIELD txt_mu_item_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 257, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mu_item_value3, .pRoot = (POBJECT_HEAD)&manual_update_con_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CONSTELLATION_QAM,
	.pString = NULL
};

//txt_mu_item_value3 ------------------------------------------------------------------------
static VACTION main_freq_item_sel_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT main_freq_item_sel_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static UINT16 txt_mu_item_value3_seltable[] = {
	RS_CONSTELLATION_16,
	RS_CONSTELLATION_32,
	RS_CONSTELLATION_64,
	RS_CONSTELLATION_128,
	RS_CONSTELLATION_256,
};
MULTISEL txt_mu_item_value3 = {
	.head = {
		.bType = OT_MULTISEL,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {468, 257, 154, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_COM_SEL_ARROW, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_sel_keymap, .pfnCallback = main_freq_item_sel_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_con_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bSelType = STRING_ID,
	.pSelTable = txt_mu_item_value3_seltable,
	.nCount = 5,
	.nSel = 0,
};

//manual_update_con_item4 ------------------------------------------------------------------------

CONTAINER manual_update_con_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 1,
		.frame = {294, 299, 343, 30},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_help, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mu_item_name4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mu_item_name4 ------------------------------------------------------------------------

TEXT_FIELD txt_mu_item_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 301, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mu_item_value4, .pRoot = (POBJECT_HEAD)&manual_update_con_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_INFO_PID,
	.pString = NULL
};

//txt_mu_item_value4 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mu_item_value4_pattern[] = "s5";
EDIT_FIELD txt_mu_item_value4 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {468, 301, 154, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_con_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mu_item_value4_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[22],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)NULL,
	.valbak = 0
};

//manual_update_help ------------------------------------------------------------------------

CONTAINER manual_update_help = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {327, 341, 309, 48},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_con
	},
	.pNextInCntn = (POBJECT_HEAD)&manual_update_comfire,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//manual_update_comfire ------------------------------------------------------------------------

TEXT_FIELD manual_update_comfire = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {314, 343, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_YELLOW_ITEM, .bHLIdx = WSTL_RCI_YELLOW_ITEM, .bSelIdx = WSTL_RCI_YELLOW_ITEM, .bGrayIdx = WSTL_RCI_YELLOW_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_modify, .pRoot = (POBJECT_HEAD)&manual_update_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_BUTTON_CONFIRM,
	.pString = NULL
};

//manual_update_modify ------------------------------------------------------------------------

TEXT_FIELD manual_update_modify = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {418, 343, 66, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_exit, .pRoot = (POBJECT_HEAD)&manual_update_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_UPDATE,
	.pString = NULL
};

//manual_update_exit ------------------------------------------------------------------------

TEXT_FIELD manual_update_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {484, 343, 78, 31},
		.style = {
			.bShowIdx = WSTL_RCI_BLUE_ITEM, .bHLIdx = WSTL_RCI_BLUE_ITEM, .bSelIdx = WSTL_RCI_BLUE_ITEM, .bGrayIdx = WSTL_RCI_BLUE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&manual_update_back, .pRoot = (POBJECT_HEAD)&manual_update_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//manual_update_back ------------------------------------------------------------------------

TEXT_FIELD manual_update_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 343, 73, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&manual_update_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};
#endif//__WIN_MANUAL_UPDATE_VEGA_H__6D81EB07_2FA2_4CCB_B6BE_ACC40C91D26B
