#ifndef _WIN_MENU_COM_H_
#define _WIN_MENU_COM_H_
#define MENU_LANGUAGE_MENU_LAN		1
#define MENU_LANGUAGE_1ST_AUDIO_LAN	2
#define MENU_LANGUAGE_2ND_AUDIO_LAN	3
#define MENU_LANGUAGE_SUB_LAN		4
#define MENU_LANGUAGE_TXT_LAN		5

#define MENU_AV_DISPLAY_MODE		1
#define MENU_AV_TV_ASPECT		2
#define MENU_AV_TV_OUTPUT		3
#define MENU_AV_RF_SYSTEM		4
#define MENU_AV_RF_CHANNEL		5

#define MENU_TIMESET_GMT_ENABLE		1
#define MENU_TIMESET_GMT_OFFESET	2
#define MENU_TIMESET_SUMMER		3
#define MENU_TIMESET_DATE		4
#define MENU_TIMESET_TIME		5
#define MENU_TIMESET_DISPLAY		6

#define MENU_PARENTAL_MENU_LOCK		1
#define MENU_PARENTAL_CHANNEL_LOCK	2
#define MENU_PARENTAL_PASSWORD		1//33
#define MENU_PARENTAL_PASSWORD2		2//44

#define MENU_OSD_SUB_DISPLAY		1
#define MENU_OSD_TIMEOUT		2
#define MENU_OSD_TRANSPARENCY		3


#endif //_WIN_MENU_COM_H_
