/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_MAINMENU_VEGA_H__B23435E8_862B_428B_8036_D8AF490F308A
#define __WIN_MAINMENU_VEGA_H__B23435E8_862B_428B_8036_D8AF490F308A


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER mm_item_con1;
extern BITMAP mm_item_bmp3;
extern CONTAINER mm_item_con2;
extern BITMAP mm_item_bmp5;
extern CONTAINER preview_con;
extern BITMAP mm_item_bmp4;
extern CONTAINER g_win_mainmenu;
extern BITMAP Bitmap_logo_top;
extern BITMAP mm_item_bmp2;
extern CONTAINER mm_item_con4;
extern BITMAP mm_item_bmp1;
extern CONTAINER mm_item_con3;
extern BITMAP Bitmap_logo_right;
extern CONTAINER mm_item_con5;
extern BITMAP Bitmap_logo_left;

//g_win_mainmenu ------------------------------------------------------------------------
static VACTION mm_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_mainmenu = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 720, 576},
		.style = {
			.bShowIdx = WSTL_TRANS_IX, .bHLIdx = WSTL_TRANS_IX, .bSelIdx = WSTL_TRANS_IX, .bGrayIdx = WSTL_TRANS_IX
		},
		.pfnKeyMap = mm_con_keymap, .pfnCallback = mm_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&Bitmap_logo_right,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//Bitmap_logo_right ------------------------------------------------------------------------

BITMAP Bitmap_logo_right = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {591, 15, 118, 534},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&Bitmap_logo_top, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_LOGO_RIGHT,
};

//Bitmap_logo_top ------------------------------------------------------------------------

BITMAP Bitmap_logo_top = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {223, 19, 407, 167},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&Bitmap_logo_left, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_LOGO_TOP,
};

//Bitmap_logo_left ------------------------------------------------------------------------

BITMAP Bitmap_logo_left = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {9, 19, 250, 391},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&preview_con, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_LOGO_LEFT,
};

//preview_con ------------------------------------------------------------------------

CONTAINER preview_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {225, 187, 413, 357},
		.style = {
			.bShowIdx = WSTL_MAINMENU_PREV_BG, .bHLIdx = WSTL_MAINMENU_PREV_BG, .bSelIdx = WSTL_MAINMENU_PREV_BG, .bGrayIdx = WSTL_MAINMENU_PREV_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mm_item_con1, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)NULL,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//mm_item_con1 ------------------------------------------------------------------------
static VACTION mm_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER mm_item_con1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 5, .bDownID = 2,
		.frame = {43, 202, 179, 49},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = mm_item_con_keymap, .pfnCallback = mm_item_con_callback,
		.pNext = (POBJECT_HEAD)&mm_item_con2, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)&mm_item_bmp1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mm_item_bmp1 ------------------------------------------------------------------------

BITMAP mm_item_bmp1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {63, 199, 167, 64},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mm_item_con1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_ICON1_B,
};

//mm_item_con2 ------------------------------------------------------------------------
static VACTION mm_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER mm_item_con2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 1, .bDownID = 3,
		.frame = {38, 259, 196, 49},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = mm_item_con_keymap, .pfnCallback = mm_item_con_callback,
		.pNext = (POBJECT_HEAD)&mm_item_con3, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)&mm_item_bmp2,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//mm_item_bmp2 ------------------------------------------------------------------------

BITMAP mm_item_bmp2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {63, 256, 167, 64},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mm_item_con2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_ICON2_B,
};

//mm_item_con3 ------------------------------------------------------------------------
static VACTION mm_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER mm_item_con3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 2, .bDownID = 4,
		.frame = {42, 316, 196, 49},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = mm_item_con_keymap, .pfnCallback = mm_item_con_callback,
		.pNext = (POBJECT_HEAD)&mm_item_con4, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)&mm_item_bmp3,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//mm_item_bmp3 ------------------------------------------------------------------------

BITMAP mm_item_bmp3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {62, 313, 167, 64},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mm_item_con3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_ICON3_B,
};

//mm_item_con4 ------------------------------------------------------------------------
static VACTION mm_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER mm_item_con4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 4, .bRightID = 4, .bUpID = 3, .bDownID = 5,
		.frame = {42, 374, 196, 49},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = mm_item_con_keymap, .pfnCallback = mm_item_con_callback,
		.pNext = (POBJECT_HEAD)&mm_item_con5, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)&mm_item_bmp4,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//mm_item_bmp4 ------------------------------------------------------------------------

BITMAP mm_item_bmp4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {62, 371, 167, 64},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mm_item_con4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_ICON4_B,
};

//mm_item_con5 ------------------------------------------------------------------------
static VACTION mm_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mm_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER mm_item_con5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 5, .bRightID = 5, .bUpID = 4, .bDownID = 1,
		.frame = {42, 431, 196, 49},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = mm_item_con_keymap, .pfnCallback = mm_item_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_mainmenu
	},
	.pNextInCntn = (POBJECT_HEAD)&mm_item_bmp5,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//mm_item_bmp5 ------------------------------------------------------------------------

BITMAP mm_item_bmp5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {62, 428, 167, 64},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mm_item_con5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_ICON5_B,
};
#endif//__WIN_MAINMENU_VEGA_H__B23435E8_862B_428B_8036_D8AF490F308A
