/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_ADVSET_VEGA_H__60FEEBD5_2A35_49A2_B3A9_35E9381991CC
#define __WIN_ADVSET_VEGA_H__60FEEBD5_2A35_49A2_B3A9_35E9381991CC


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD advset_con_txt_item0;
extern CONTAINER g_win_advset;
extern TEXT_FIELD advset_con_txt_item4;
extern BITMAP advset_bmap1;
extern TEXT_FIELD advset_con_txt_item2;
extern TEXT_FIELD advset_con_txt_item1;
extern CONTAINER win_advset_con;
extern TEXT_FIELD advset_con_txt_item3;
extern TEXT_FIELD advset_title;
extern BITMAP advset_bmap;

//g_win_advset ------------------------------------------------------------------------
static VACTION advset_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT advset_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_advset = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 720, 576},
		.style = {
			.bShowIdx = WSTL_TRANS_IX, .bHLIdx = WSTL_TRANS_IX, .bSelIdx = WSTL_TRANS_IX, .bGrayIdx = WSTL_TRANS_IX
		},
		.pfnKeyMap = advset_keymap, .pfnCallback = advset_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&advset_bmap,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//advset_bmap ------------------------------------------------------------------------

BITMAP advset_bmap = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {41, 21, 243, 90},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&win_advset_con, .pRoot = (POBJECT_HEAD)&g_win_advset
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_SEL_ITEM_ENTRY_MENU_TITLE,
};

//win_advset_con ------------------------------------------------------------------------
static VACTION advset_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT advset_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER win_advset_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {94, 111, 188, 254},
		.style = {
			.bShowIdx = WSTL_LIST_BG, .bHLIdx = WSTL_LIST_BG, .bSelIdx = WSTL_LIST_BG, .bGrayIdx = WSTL_LIST_BG
		},
		.pfnKeyMap = advset_con_keymap, .pfnCallback = advset_con_callback,
		.pNext = (POBJECT_HEAD)&advset_bmap1, .pRoot = (POBJECT_HEAD)&g_win_advset
	},
	.pNextInCntn = (POBJECT_HEAD)&advset_con_txt_item0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//advset_con_txt_item0 ------------------------------------------------------------------------

TEXT_FIELD advset_con_txt_item0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 2,
		.frame = {121, 136, 161, 35},
		.style = {
			.bShowIdx = WSTL_SEL_ITEM_SH, .bHLIdx = WSTL_SEL_ITEM_HL, .bSelIdx = WSTL_SEL_ITEM_SH, .bGrayIdx = WSTL_SEL_ITEM_SH
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&advset_con_txt_item1, .pRoot = (POBJECT_HEAD)&win_advset_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_DISPLAY_SETTINGS,
	.pString = NULL
};

//advset_con_txt_item1 ------------------------------------------------------------------------

TEXT_FIELD advset_con_txt_item1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {121, 176, 161, 35},
		.style = {
			.bShowIdx = WSTL_SEL_ITEM_SH, .bHLIdx = WSTL_SEL_ITEM_HL, .bSelIdx = WSTL_SEL_ITEM_SH, .bGrayIdx = WSTL_SEL_ITEM_SH
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&advset_con_txt_item2, .pRoot = (POBJECT_HEAD)&win_advset_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_AUDIO_SETTINTS,
	.pString = NULL
};

//advset_con_txt_item2 ------------------------------------------------------------------------

TEXT_FIELD advset_con_txt_item2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {121, 216, 161, 35},
		.style = {
			.bShowIdx = WSTL_SEL_ITEM_SH, .bHLIdx = WSTL_SEL_ITEM_HL, .bSelIdx = WSTL_SEL_ITEM_SH, .bGrayIdx = WSTL_SEL_ITEM_SH
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&advset_con_txt_item3, .pRoot = (POBJECT_HEAD)&win_advset_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_TOOLS_FACTORY_SETTING,
	.pString = NULL
};

//advset_con_txt_item3 ------------------------------------------------------------------------

TEXT_FIELD advset_con_txt_item3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {121, 256, 161, 35},
		.style = {
			.bShowIdx = WSTL_SEL_ITEM_SH, .bHLIdx = WSTL_SEL_ITEM_HL, .bSelIdx = WSTL_SEL_ITEM_SH, .bGrayIdx = WSTL_SEL_ITEM_SH
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&advset_con_txt_item4, .pRoot = (POBJECT_HEAD)&win_advset_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY_SETTINGS,
	.pString = NULL
};

//advset_con_txt_item4 ------------------------------------------------------------------------

TEXT_FIELD advset_con_txt_item4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 1,
		.frame = {121, 296, 161, 35},
		.style = {
			.bShowIdx = WSTL_SEL_ITEM_SH, .bHLIdx = WSTL_SEL_ITEM_HL, .bSelIdx = WSTL_SEL_ITEM_SH, .bGrayIdx = WSTL_SEL_ITEM_SH
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&win_advset_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_MANUAL_UPDATE,
	.pString = NULL
};

//advset_bmap1 ------------------------------------------------------------------------

BITMAP advset_bmap1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {94, 365, 188, 30},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&advset_title, .pRoot = (POBJECT_HEAD)&g_win_advset
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_SEL_ITEM_ENTRY_MENU_BOTTOM,
};

//advset_title ------------------------------------------------------------------------

TEXT_FIELD advset_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {127, 72, 112, 20},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_advset
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_ADVANCED_SETTINGS,
	.pString = NULL
};
#endif//__WIN_ADVSET_VEGA_H__60FEEBD5_2A35_49A2_B3A9_35E9381991CC
