/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_NEW_SIGNAL_H__21E1F672_832E_4C43_A873_4152910F029E
#define __WIN_NEW_SIGNAL_H__21E1F672_832E_4C43_A873_4152910F029E


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD txt_signal_item1;
extern EDIT_FIELD txt_signal_item11;
extern TEXT_FIELD txt_signal_item2;
extern TEXT_FIELD txt_signal_title3;
extern TEXT_FIELD txt_signal_title4;
extern TEXT_FIELD txt_signal_title2;
extern CONTAINER main_item;
extern CONTAINER main_list_item0;
extern CONTAINER main_list_item2;
extern TEXT_FIELD signal_txt_BER;
extern MULTISEL txt_signal_item22;
extern CONTAINER main_list_item1;
extern TEXT_FIELD signal_txt_level;
extern TEXT_FIELD txt_signal_item0;
extern TEXT_FIELD signal_txt_BER22;
extern TEXT_FIELD signal_txt_CN11;
extern TEXT_FIELD signal_txt_level00;
extern TEXT_FIELD txt_signal_title0;
extern TEXT_FIELD txt_signal_title1;
extern CONTAINER win_signal_level;
extern EDIT_FIELD txt_signal_item00;
extern CONTAINER g_win_signal0;
extern TEXT_FIELD signal_txt_CN;

//g_win_signal0 ------------------------------------------------------------------------
static VACTION signal_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT signal_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_signal0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {276, 52, 406, 437},
		.style = {
			.bShowIdx = WSTL_EMIAL_OL_CON, .bHLIdx = WSTL_EMIAL_OL_CON, .bSelIdx = WSTL_EMIAL_OL_CON, .bGrayIdx = WSTL_EMIAL_OL_CON
		},
		.pfnKeyMap = signal_keymap, .pfnCallback = signal_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&main_item,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_item ------------------------------------------------------------------------
static VACTION item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT item_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER main_item = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {423, 99, 253, 124},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_RCI_C_GRAY, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = item_keymap, .pfnCallback = item_callback,
		.pNext = (POBJECT_HEAD)&win_signal_level, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.pNextInCntn = (POBJECT_HEAD)&main_list_item0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_list_item0 ------------------------------------------------------------------------

CONTAINER main_list_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 3, .bDownID = 2,
		.frame = {423, 105, 253, 30},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_RCI_C_GRAY, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_list_item1, .pRoot = (POBJECT_HEAD)&main_item
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_signal_item0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_signal_item0 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_item0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {425, 105, 101, 30},
		.style = {
			.bShowIdx = WSTL_YU_COM_SEL_NAME, .bHLIdx = WSTL_YU_COM_SEL_NAME, .bSelIdx = WSTL_YU_COM_SEL_NAME, .bGrayIdx = WSTL_YU_COM_SEL_NAME
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_item00, .pRoot = (POBJECT_HEAD)&main_list_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY,
	.pString = NULL
};

//txt_signal_item00 ------------------------------------------------------------------------
static VACTION main_signal_item_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_signal_item00_pattern[] = "f32";
static const UINT8 txt_signal_item00_Suffix[] = {0, 77, 0, 72, 0, 90, 0, 0}; //Suffix = MHZ
EDIT_FIELD txt_signal_item00 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {526, 105, 150, 30},
		.style = {
			.bShowIdx = WSTL_YU_SEL, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_YU_SEL, .bGrayIdx = WSTL_YU_SEL
		},
		.pfnKeyMap = main_signal_item_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_list_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_signal_item00_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[0],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_signal_item00_Suffix,
	.valbak = 0
};

//main_list_item1 ------------------------------------------------------------------------

CONTAINER main_list_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 1, .bDownID = 3,
		.frame = {423, 146, 253, 30},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_RCI_C_GRAY, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_list_item2, .pRoot = (POBJECT_HEAD)&main_item
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_signal_item1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_signal_item1 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_item1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {425, 146, 101, 30},
		.style = {
			.bShowIdx = WSTL_YU_COM_SEL_NAME, .bHLIdx = WSTL_YU_COM_SEL_NAME, .bSelIdx = WSTL_YU_COM_SEL_NAME, .bGrayIdx = WSTL_YU_COM_SEL_NAME
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_item11, .pRoot = (POBJECT_HEAD)&main_list_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_INFO_SYMBOL,
	.pString = NULL
};

//txt_signal_item11 ------------------------------------------------------------------------
static VACTION main_signal_item_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_signal_item11_pattern[] = "s5";
static const UINT8 txt_signal_item11_Suffix[] = {0, 75, 0, 66, 0, 97, 0, 117, 0, 100, 0, 0}; //Suffix = KBaud
EDIT_FIELD txt_signal_item11 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {526, 146, 150, 30},
		.style = {
			.bShowIdx = WSTL_YU_SEL, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_YU_SEL, .bGrayIdx = WSTL_YU_SEL
		},
		.pfnKeyMap = main_signal_item_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_list_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_signal_item11_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[1],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_signal_item11_Suffix,
	.valbak = 0
};

//main_list_item2 ------------------------------------------------------------------------

CONTAINER main_list_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 2, .bDownID = 1,
		.frame = {423, 191, 253, 30},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_RCI_C_GRAY, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_item
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_signal_item2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_signal_item2 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_item2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {425, 191, 101, 30},
		.style = {
			.bShowIdx = WSTL_YU_COM_SEL_NAME, .bHLIdx = WSTL_YU_COM_SEL_NAME, .bSelIdx = WSTL_YU_COM_SEL_NAME, .bGrayIdx = WSTL_YU_COM_SEL_NAME
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_item22, .pRoot = (POBJECT_HEAD)&main_list_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_YU_WAY,
	.pString = NULL
};

//txt_signal_item22 ------------------------------------------------------------------------
static VACTION main_signal_sel_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT main_signal_sel_item_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static UINT16 txt_signal_item22_seltable[] = {
	RS_CONSTELLATION_16,
	RS_CONSTELLATION_32,
	RS_CONSTELLATION_64,
	RS_CONSTELLATION_128,
	RS_CONSTELLATION_256,
};
MULTISEL txt_signal_item22 = {
	.head = {
		.bType = OT_MULTISEL,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {526, 191, 150, 30},
		.style = {
			.bShowIdx = WSTL_YU_SEL, .bHLIdx = WSTL_COM_SEL_ARROW, .bSelIdx = WSTL_YU_SEL, .bGrayIdx = WSTL_YU_SEL
		},
		.pfnKeyMap = main_signal_sel_item_keymap, .pfnCallback = main_signal_sel_item_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_list_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bSelType = STRING_ID,
	.pSelTable = txt_signal_item22_seltable,
	.nCount = 5,
	.nSel = 0,
};

//win_signal_level ------------------------------------------------------------------------

CONTAINER win_signal_level = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {423, 225, 253, 165},
		.style = {
			.bShowIdx = WSTL_YU_WHITE_FRAME, .bHLIdx = WSTL_YU_WHITE_FRAME, .bSelIdx = WSTL_YU_WHITE_FRAME, .bGrayIdx = WSTL_YU_WHITE_FRAME
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_title0, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_txt_level,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//signal_txt_level ------------------------------------------------------------------------

TEXT_FIELD signal_txt_level = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {425, 243, 100, 23},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_txt_CN, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_INFO_SIGNAL_INTENSITY,
	.pString = NULL
};

//signal_txt_CN ------------------------------------------------------------------------

TEXT_FIELD signal_txt_CN = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {425, 284, 99, 25},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_txt_BER, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_YU_SIGNAL,
	.pString = NULL
};

//signal_txt_BER ------------------------------------------------------------------------

TEXT_FIELD signal_txt_BER = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {426, 325, 98, 25},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_txt_level00, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_ERROR_RATIO,
	.pString = NULL
};

//signal_txt_level00 ------------------------------------------------------------------------

TEXT_FIELD signal_txt_level00 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {620, 244, 53, 25},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_txt_CN11, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_YU_DBuV,
	.pString = NULL
};

//signal_txt_CN11 ------------------------------------------------------------------------

TEXT_FIELD signal_txt_CN11 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {620, 284, 53, 24},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_txt_BER22, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_YU_DB,
	.pString = NULL
};

//signal_txt_BER22 ------------------------------------------------------------------------

TEXT_FIELD signal_txt_BER22 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {620, 326, 53, 25},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&win_signal_level
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_YU_E,
	.pString = NULL
};

//txt_signal_title0 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_title0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {318, 58, 119, 25},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_title1, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SIGNAL_CHECK,
	.pString = NULL
};

//txt_signal_title1 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_title1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {292, 422, 112, 33},
		.style = {
			.bShowIdx = WSTL_RCI_YELLOW_ITEM, .bHLIdx = WSTL_RCI_YELLOW_ITEM, .bSelIdx = WSTL_RCI_YELLOW_ITEM, .bGrayIdx = WSTL_RCI_YELLOW_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_title2, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CTI_BUTTON_CONFIRM,
	.pString = NULL
};

//txt_signal_title2 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_title2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {406, 422, 66, 33},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_title3, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_CHANGE,
	.pString = NULL
};

//txt_signal_title3 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_title3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {494, 422, 112, 31},
		.style = {
			.bShowIdx = WSTL_HIGHT_EMIAL, .bHLIdx = WSTL_HIGHT_EMIAL, .bSelIdx = WSTL_HIGHT_EMIAL, .bGrayIdx = WSTL_HIGHT_EMIAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_signal_title4, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//txt_signal_title4 ------------------------------------------------------------------------

TEXT_FIELD txt_signal_title4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {608, 422, 66, 33},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_signal0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};
#endif//__WIN_NEW_SIGNAL_H__21E1F672_832E_4C43_A873_4152910F029E
