/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_CHAN_EDIT_OBJ_H__C148F135_4C9F_4887_8C1C_D5E04A31EFD1
#define __WIN_CHAN_EDIT_OBJ_H__C148F135_4C9F_4887_8C1C_D5E04A31EFD1


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD edit_exit;
extern CONTAINER chanedit_item10;
extern TEXT_FIELD edit_back;
extern TEXT_FIELD chanedit_name9;
extern TEXT_FIELD chanedit_idx3;
extern CONTAINER g_win_chanedit;
extern TEXT_FIELD edit_modify;
extern CONTAINER chanedit_item7;
extern TEXT_FIELD chanedit_idx10;
extern TEXT_FIELD chanedit_name8;
extern CONTAINER chanedit_action;
extern SCROLL_BAR chanedit_scb;
extern BITMAP chanedit_flagb6;
extern BITMAP chanedit_flagb10;
extern BITMAP chanedit_flaga7;
extern BITMAP chanedit_flaga10;
extern TEXT_FIELD chanedit_idx4;
extern TEXT_FIELD chanedit_name3;
extern BITMAP chanedit_flagb9;
extern BITMAP chanedit_flaga1;
extern CONTAINER chanedit_item1;
extern TEXT_FIELD chanedit_idx9;
extern BITMAP chanedit_flagb5;
extern CONTAINER chanedit_item2;
extern TEXT_FIELD chanedit_name2;
extern TEXT_FIELD chanedit_idx7;
extern OBJLIST chanedit_ol;
extern BITMAP chanedit_flaga3;
extern TEXT_FIELD chanedit_name6;
extern CONTAINER chanedit_item5;
extern TEXT_FIELD chanedit_name10;
extern TEXT_FIELD edit_comfire;
extern BITMAP chanedit_flaga6;
extern TEXT_FIELD chanedit_idx5;
extern CONTAINER chanedit_item4;
extern BITMAP chanedit_flaga4;
extern CONTAINER chanedit_item8;
extern BITMAP chanedit_flagb7;
extern BITMAP chanedit_flagb2;
extern TEXT_FIELD chanedit_name7;
extern BITMAP chanedit_flagb4;
extern BITMAP chanedit_flagb3;
extern TEXT_FIELD chanedit_idx1;
extern CONTAINER chanedit_item9;
extern TEXT_FIELD chanedit_name1;
extern BITMAP chanedit_flaga2;
extern BITMAP chanedit_flagb8;
extern CONTAINER chanedit_item6;
extern BITMAP chanedit_flaga5;
extern TEXT_FIELD chanedit_idx6;
extern BITMAP chanedit_flaga9;
extern TEXT_FIELD chanedit_name4;
extern BITMAP chanedit_flaga8;
extern TEXT_FIELD chanedit_name5;
extern TEXT_FIELD chanedit_idx8;
extern CONTAINER chanedit_item3;
extern BITMAP chanedit_flagb1;
extern TEXT_FIELD chanedit_idx2;

//g_win_chanedit ------------------------------------------------------------------------
static VACTION chanedit_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT chanedit_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_chanedit = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {280, 26, 394, 501},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = chanedit_keymap, .pfnCallback = chanedit_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_ol,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//chanedit_ol ------------------------------------------------------------------------
static VACTION chanedit_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT chanedit_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD chanedit_ol_ListField[] = {
	(POBJECT_HEAD)&chanedit_item1,
	(POBJECT_HEAD)&chanedit_item2,
	(POBJECT_HEAD)&chanedit_item3,
	(POBJECT_HEAD)&chanedit_item4,
	(POBJECT_HEAD)&chanedit_item5,
	(POBJECT_HEAD)&chanedit_item6,
	(POBJECT_HEAD)&chanedit_item7,
	(POBJECT_HEAD)&chanedit_item8,
	(POBJECT_HEAD)&chanedit_item9,
	(POBJECT_HEAD)&chanedit_item10,
};
OBJLIST chanedit_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {280, 29, 384, 364},
		.style = {
			.bShowIdx = WSTL_RCI_LAST_WIN_BG, .bHLIdx = WSTL_RCI_LAST_WIN_BG, .bSelIdx = WSTL_RCI_LAST_WIN_BG, .bGrayIdx = WSTL_RCI_LAST_WIN_BG
		},
		.pfnKeyMap = chanedit_list_keymap, .pfnCallback = chanedit_list_callback,
		.pNext = (POBJECT_HEAD)&chanedit_action, .pRoot = (POBJECT_HEAD)&g_win_chanedit
	},
	.pListField = chanedit_ol_ListField,
	.scrollBar = &chanedit_scb,
	.bListStyle = LIST_VER | LIST_SINGLE_SLECT | LIST_ITEMS_NOCOMPLETE | LIST_SCROLL | LIST_GRID | LIST_FOCUS_FIRST | LIST_PAGE_KEEP_CURITEM | LIST_FULL_PAGE,
	.wDep = 10, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//chanedit_item1 ------------------------------------------------------------------------

CONTAINER chanedit_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 10, .bDownID = 2,
		.frame = {290, 44, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_RCI_C_GRAY, .bGrayIdx = WSTL_RCI_C_GRAY
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item2, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx1 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 45, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name1, .pRoot = (POBJECT_HEAD)&chanedit_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0] 
};

//chanedit_name1 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 45, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga1, .pRoot = (POBJECT_HEAD)&chanedit_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10] 
};

//chanedit_flaga1 ------------------------------------------------------------------------

BITMAP chanedit_flaga1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 44, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb1, .pRoot = (POBJECT_HEAD)&chanedit_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb1 ------------------------------------------------------------------------

BITMAP chanedit_flagb1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 44, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item2 ------------------------------------------------------------------------

CONTAINER chanedit_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {290, 78, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item3, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx2 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 78, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name2, .pRoot = (POBJECT_HEAD)&chanedit_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1] 
};

//chanedit_name2 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 78, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga2, .pRoot = (POBJECT_HEAD)&chanedit_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11] 
};

//chanedit_flaga2 ------------------------------------------------------------------------

BITMAP chanedit_flaga2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 78, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb2, .pRoot = (POBJECT_HEAD)&chanedit_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb2 ------------------------------------------------------------------------

BITMAP chanedit_flagb2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 78, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item3 ------------------------------------------------------------------------

CONTAINER chanedit_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {290, 112, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item4, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx3 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 112, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name3, .pRoot = (POBJECT_HEAD)&chanedit_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2] 
};

//chanedit_name3 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 112, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga3, .pRoot = (POBJECT_HEAD)&chanedit_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12] 
};

//chanedit_flaga3 ------------------------------------------------------------------------

BITMAP chanedit_flaga3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 112, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb3, .pRoot = (POBJECT_HEAD)&chanedit_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb3 ------------------------------------------------------------------------

BITMAP chanedit_flagb3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 112, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item4 ------------------------------------------------------------------------

CONTAINER chanedit_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {289, 146, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item5, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx4 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 146, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name4, .pRoot = (POBJECT_HEAD)&chanedit_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3] 
};

//chanedit_name4 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 146, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga4, .pRoot = (POBJECT_HEAD)&chanedit_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13] 
};

//chanedit_flaga4 ------------------------------------------------------------------------

BITMAP chanedit_flaga4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 146, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb4, .pRoot = (POBJECT_HEAD)&chanedit_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb4 ------------------------------------------------------------------------

BITMAP chanedit_flagb4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 146, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item5 ------------------------------------------------------------------------

CONTAINER chanedit_item5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {289, 180, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item6, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx5,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx5 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 180, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name5, .pRoot = (POBJECT_HEAD)&chanedit_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4] 
};

//chanedit_name5 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 180, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga5, .pRoot = (POBJECT_HEAD)&chanedit_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14] 
};

//chanedit_flaga5 ------------------------------------------------------------------------

BITMAP chanedit_flaga5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 180, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb5, .pRoot = (POBJECT_HEAD)&chanedit_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb5 ------------------------------------------------------------------------

BITMAP chanedit_flagb5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 180, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item6 ------------------------------------------------------------------------

CONTAINER chanedit_item6 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 7,
		.frame = {289, 214, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item7, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx6,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx6 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 214, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name6, .pRoot = (POBJECT_HEAD)&chanedit_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5] 
};

//chanedit_name6 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 214, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga6, .pRoot = (POBJECT_HEAD)&chanedit_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15] 
};

//chanedit_flaga6 ------------------------------------------------------------------------

BITMAP chanedit_flaga6 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 214, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb6, .pRoot = (POBJECT_HEAD)&chanedit_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb6 ------------------------------------------------------------------------

BITMAP chanedit_flagb6 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 214, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item7 ------------------------------------------------------------------------

CONTAINER chanedit_item7 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 7, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 8,
		.frame = {290, 248, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item8, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx7,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx7 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 248, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name7, .pRoot = (POBJECT_HEAD)&chanedit_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6] 
};

//chanedit_name7 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 248, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga7, .pRoot = (POBJECT_HEAD)&chanedit_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16] 
};

//chanedit_flaga7 ------------------------------------------------------------------------

BITMAP chanedit_flaga7 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 248, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb7, .pRoot = (POBJECT_HEAD)&chanedit_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb7 ------------------------------------------------------------------------

BITMAP chanedit_flagb7 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 248, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item8 ------------------------------------------------------------------------

CONTAINER chanedit_item8 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 8, .bLeftID = 0, .bRightID = 0, .bUpID = 7, .bDownID = 9,
		.frame = {289, 282, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item9, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx8,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx8 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 282, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name8, .pRoot = (POBJECT_HEAD)&chanedit_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7] 
};

//chanedit_name8 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 282, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga8, .pRoot = (POBJECT_HEAD)&chanedit_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17] 
};

//chanedit_flaga8 ------------------------------------------------------------------------

BITMAP chanedit_flaga8 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 282, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb8, .pRoot = (POBJECT_HEAD)&chanedit_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb8 ------------------------------------------------------------------------

BITMAP chanedit_flagb8 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 282, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item9 ------------------------------------------------------------------------

CONTAINER chanedit_item9 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 9, .bLeftID = 0, .bRightID = 0, .bUpID = 8, .bDownID = 10,
		.frame = {289, 316, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_item10, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx9,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx9 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx9 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 316, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name9, .pRoot = (POBJECT_HEAD)&chanedit_item9
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8] 
};

//chanedit_name9 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name9 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 316, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga9, .pRoot = (POBJECT_HEAD)&chanedit_item9
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[18] 
};

//chanedit_flaga9 ------------------------------------------------------------------------

BITMAP chanedit_flaga9 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 316, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb9, .pRoot = (POBJECT_HEAD)&chanedit_item9
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb9 ------------------------------------------------------------------------

BITMAP chanedit_flagb9 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 316, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item9
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_item10 ------------------------------------------------------------------------

CONTAINER chanedit_item10 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 10, .bLeftID = 0, .bRightID = 0, .bUpID = 9, .bDownID = 1,
		.frame = {289, 350, 345, 27},
		.style = {
			.bShowIdx = WSTL_RCI_C_GRAY, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_scb, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&chanedit_idx10,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//chanedit_idx10 ------------------------------------------------------------------------

TEXT_FIELD chanedit_idx10 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {293, 350, 50, 27},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_name10, .pRoot = (POBJECT_HEAD)&chanedit_item10
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9] 
};

//chanedit_name10 ------------------------------------------------------------------------

TEXT_FIELD chanedit_name10 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {347, 350, 200, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flaga10, .pRoot = (POBJECT_HEAD)&chanedit_item10
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[19] 
};

//chanedit_flaga10 ------------------------------------------------------------------------

BITMAP chanedit_flaga10 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {551, 350, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&chanedit_flagb10, .pRoot = (POBJECT_HEAD)&chanedit_item10
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_flagb10 ------------------------------------------------------------------------

BITMAP chanedit_flagb10 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {595, 350, 40, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_item10
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//chanedit_scb ------------------------------------------------------------------------

SCROLL_BAR chanedit_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {639, 45, 12, 334},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_ol
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 10,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 280},
	.nMax = 100, .nPos = 1
};

//chanedit_action ------------------------------------------------------------------------

CONTAINER chanedit_action = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {280, 384, 384, 64},
		.style = {
			.bShowIdx = WSTL_RCI_LAST_WIN_BG_NOTOP, .bHLIdx = WSTL_RCI_LAST_WIN_BG, .bSelIdx = WSTL_RCI_LAST_WIN_BG, .bGrayIdx = WSTL_RCI_LAST_WIN_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_chanedit
	},
	.pNextInCntn = (POBJECT_HEAD)&edit_comfire,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//edit_comfire ------------------------------------------------------------------------

TEXT_FIELD edit_comfire = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {294, 397, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_YELLOW_ITEM, .bHLIdx = WSTL_RCI_YELLOW_ITEM, .bSelIdx = WSTL_RCI_YELLOW_ITEM, .bGrayIdx = WSTL_RCI_YELLOW_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&edit_modify, .pRoot = (POBJECT_HEAD)&chanedit_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_BUTTON_CONFIRM,
	.pString = NULL
};

//edit_modify ------------------------------------------------------------------------

TEXT_FIELD edit_modify = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {382, 397, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&edit_exit, .pRoot = (POBJECT_HEAD)&chanedit_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_CHANGE,
	.pString = NULL
};

//edit_exit ------------------------------------------------------------------------

TEXT_FIELD edit_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {470, 397, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_BLUE_ITEM, .bHLIdx = WSTL_RCI_BLUE_ITEM, .bSelIdx = WSTL_RCI_BLUE_ITEM, .bGrayIdx = WSTL_RCI_BLUE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&edit_back, .pRoot = (POBJECT_HEAD)&chanedit_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//edit_back ------------------------------------------------------------------------

TEXT_FIELD edit_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {557, 398, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&chanedit_action
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};
#endif//__WIN_CHAN_EDIT_OBJ_H__C148F135_4C9F_4887_8C1C_D5E04A31EFD1
