/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_MAIN_FREQ_OBJ_H__AFEBD8DD_F4F4_4778_A436_7F772C2B1B7A
#define __WIN_MAIN_FREQ_OBJ_H__AFEBD8DD_F4F4_4778_A436_7F772C2B1B7A


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER main_freq_con_item2;
extern TEXT_FIELD txt_mf_item_name4;
extern EDIT_FIELD txt_mf_item_value1;
extern EDIT_FIELD txt_mf_item_value2;
extern CONTAINER main_freq_con_items;
extern CONTAINER main_freq_con_item1;
extern TEXT_FIELD txt_mf_item_name2;
extern CONTAINER main_freq_con_item4;
extern TEXT_FIELD txt_mf_item_name1;
extern TEXT_FIELD txt_mf_item_name3;
extern CONTAINER main_freq_con_item3;
extern EDIT_FIELD txt_mf_item_value4;
extern MULTISEL txt_mf_item_value3;
extern CONTAINER g_win_main_freq;

//g_win_main_freq ------------------------------------------------------------------------
static VACTION win_common_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_main_freq_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_main_freq = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_SEARCH_BG_CON, .bHLIdx = WSTL_SEARCH_BG_CON, .bSelIdx = WSTL_SEARCH_BG_CON, .bGrayIdx = WSTL_SEARCH_BG_CON
		},
		.pfnKeyMap = win_common_item_keymap, .pfnCallback = win_main_freq_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&main_freq_con_items,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_freq_con_items ------------------------------------------------------------------------
static VACTION con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER main_freq_con_items = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {66, 102, 604, 273},
		.style = {
			.bShowIdx = WSTL_WIN_2, .bHLIdx = WSTL_WIN_2, .bSelIdx = WSTL_WIN_2, .bGrayIdx = WSTL_WIN_2
		},
		.pfnKeyMap = con_keymap, .pfnCallback = con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_main_freq
	},
	.pNextInCntn = (POBJECT_HEAD)&main_freq_con_item1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_freq_con_item1 ------------------------------------------------------------------------

CONTAINER main_freq_con_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 4, .bDownID = 2,
		.frame = {76, 132, 574, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item2, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name1 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {86, 132, 328, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value1, .pRoot = (POBJECT_HEAD)&main_freq_con_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY,
	.pString = NULL
};

//txt_mf_item_value1 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mf_item_value1_pattern[] = "f32";
static const UINT8 txt_mf_item_value1_Suffix[] = {0, 77, 0, 72, 0, 122, 0, 0}; //Suffix = MHz
EDIT_FIELD txt_mf_item_value1 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {464, 132, 154, 30},
		.style = {
			.bShowIdx = WSTL_TXT_11, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_TXT_11, .bGrayIdx = WSTL_TXT_11
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mf_item_value1_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[20],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mf_item_value1_Suffix,
	.valbak = 0
};

//main_freq_con_item2 ------------------------------------------------------------------------

CONTAINER main_freq_con_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 1, .bDownID = 3,
		.frame = {76, 192, 574, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item3, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name2 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {86, 192, 328, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value2, .pRoot = (POBJECT_HEAD)&main_freq_con_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SEARCH_COD_SYMBOL,
	.pString = NULL
};

//txt_mf_item_value2 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mf_item_value2_pattern[] = "s5";
static const UINT8 txt_mf_item_value2_Suffix[] = {0, 75, 0, 66, 0, 97, 0, 117, 0, 100, 0, 0}; //Suffix = KBaud
EDIT_FIELD txt_mf_item_value2 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {464, 192, 154, 30},
		.style = {
			.bShowIdx = WSTL_TXT_11, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_TXT_11, .bGrayIdx = WSTL_TXT_11
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mf_item_value2_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[21],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mf_item_value2_Suffix,
	.valbak = 0
};

//main_freq_con_item3 ------------------------------------------------------------------------

CONTAINER main_freq_con_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 2, .bDownID = 4,
		.frame = {76, 252, 574, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item4, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name3,
	.FocusObjectID = 3,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name3 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {86, 252, 328, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value3, .pRoot = (POBJECT_HEAD)&main_freq_con_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CONSTELLATION,
	.pString = NULL
};

//txt_mf_item_value3 ------------------------------------------------------------------------
static VACTION main_freq_item_sel_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT main_freq_item_sel_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static UINT16 txt_mf_item_value3_seltable[] = {
	RS_CONSTELLATION_16,
	RS_CONSTELLATION_32,
	RS_CONSTELLATION_64,
	RS_CONSTELLATION_128,
	RS_CONSTELLATION_256,
};
MULTISEL txt_mf_item_value3 = {
	.head = {
		.bType = OT_MULTISEL,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {464, 252, 154, 30},
		.style = {
			.bShowIdx = WSTL_TXT_11, .bHLIdx = WSTL_BUTTON_5, .bSelIdx = WSTL_TXT_11, .bGrayIdx = WSTL_TXT_11
		},
		.pfnKeyMap = main_freq_item_sel_keymap, .pfnCallback = main_freq_item_sel_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bSelType = STRING_ID,
	.pSelTable = txt_mf_item_value3_seltable,
	.nCount = 5,
	.nSel = 0,
};

//main_freq_con_item4 ------------------------------------------------------------------------

CONTAINER main_freq_con_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 4, .bRightID = 4, .bUpID = 3, .bDownID = 1,
		.frame = {76, 308, 574, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name4 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {86, 308, 328, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value4, .pRoot = (POBJECT_HEAD)&main_freq_con_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_REGION,
	.pString = NULL
};

//txt_mf_item_value4 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mf_item_value4_pattern[] = "s2";
EDIT_FIELD txt_mf_item_value4 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {464, 308, 154, 30},
		.style = {
			.bShowIdx = WSTL_TXT_11, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_TXT_11, .bGrayIdx = WSTL_TXT_11
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 4,
	.pcsPattern = txt_mf_item_value4_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[22],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)NULL,
	.valbak = 0
};
#endif//__WIN_MAIN_FREQ_OBJ_H__AFEBD8DD_F4F4_4778_A436_7F772C2B1B7A
