/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_NVOD_OBJ_H__68611DFF_18FD_44DD_9E61_87DE5EF90142
#define __WIN_NVOD_OBJ_H__68611DFF_18FD_44DD_9E61_87DE5EF90142


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern MULTI_TEXT nvod_ref_event_detail;
extern TEXT_FIELD nvod_sch_time0;
extern TEXT_FIELD nvod_sch_status3;
extern BITMAP nvod_mute_bmp;
extern CONTAINER nvod_prg_item4;
extern BITMAP nvod_book_bmp2;
extern OBJLIST nvod_sch_ol;
extern TEXT_FIELD nvod_prg_idx4;
extern CONTAINER nvod_ref_event_con;
extern CONTAINER g_win_nvod;
extern TEXT_FIELD nvod_sch_date2;
extern TEXT_FIELD nvod_prg_name0;
extern BITMAP nvod_book_bmp3;
extern TEXT_FIELD nvod_prg_name3;
extern CONTAINER nvod_prg_item3;
extern TEXT_FIELD nvod_prg_idx0;
extern TEXT_FIELD nvod_time_remain;
extern TEXT_FIELD nvod_sch_title_time;
extern TEXT_FIELD nvod_prg_name1;
extern TEXT_FIELD nvod_sch_status4;
extern BITMAP nvod_book_bmp4;
extern TEXT_FIELD nvod_sch_time4;
extern CONTAINER nvod_sch_item0;
extern TEXT_FIELD nvod_sch_date4;
extern CONTAINER nvod_prg_item2;
extern CONTAINER nvod_sch_item4;
extern CONTAINER nvod_sch_title;
extern BITMAP nvod_book_bmp0;
extern TEXT_FIELD nvod_sch_date3;
extern SCROLL_BAR nvod_sch_scb;
extern CONTAINER nvod_prg_item0;
extern SCROLL_BAR nvod_prg_scb;
extern CONTAINER nvod_sch_item3;
extern TEXT_FIELD nvod_sch_status2;
extern TEXT_FIELD nvod_sch_date0;
extern TEXT_FIELD nvod_sch_title_date;
extern TEXT_FIELD nvod_prg_idx1;
extern TEXT_FIELD nvod_prg_idx3;
extern TEXT_FIELD nvod_sch_time1;
extern OBJLIST nvod_ref_event_ol;
extern TEXT_FIELD nvod_prg_name4;
extern TEXT_FIELD nvod_prg_idx2;
extern TEXT_FIELD nvod_sch_date1;
extern CONTAINER nvod_sch_item2;
extern TEXT_FIELD nvod_sch_title_status;
extern TEXT_FIELD nvod_sch_status0;
extern BITMAP nvod_cur_prog_bmp;
extern CONTAINER nvod_prg_item1;
extern BITMAP nvod_book_bmp1;
extern TEXT_FIELD nvod_sch_time2;
extern TEXT_FIELD nvod_prg_name2;
extern TEXT_FIELD nvod_sch_status1;
extern TEXT_FIELD nvod_sch_time3;
extern TEXT_FIELD nvod_help_info;
extern CONTAINER nvod_sch_item1;

//g_win_nvod ------------------------------------------------------------------------
static VACTION nvod_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_nvod_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_nvod = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_COMMON_BACK_2, .bHLIdx = WSTL_COMMON_BACK_2, .bSelIdx = WSTL_COMMON_BACK_2, .bGrayIdx = WSTL_COMMON_BACK_2
		},
		.pfnKeyMap = nvod_keymap, .pfnCallback = win_nvod_callback,
		.pNext = (POBJECT_HEAD)&nvod_time_remain, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_ref_event_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//nvod_ref_event_con ------------------------------------------------------------------------

CONTAINER nvod_ref_event_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {66, 98, 364, 187},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_title, .pRoot = (POBJECT_HEAD)&g_win_nvod
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_ref_event_ol,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_ref_event_ol ------------------------------------------------------------------------
static VACTION nvod_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_ref_event_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD nvod_ref_event_ol_ListField[] = {
	(POBJECT_HEAD)&nvod_prg_item0,
	(POBJECT_HEAD)&nvod_prg_item1,
	(POBJECT_HEAD)&nvod_prg_item2,
	(POBJECT_HEAD)&nvod_prg_item3,
	(POBJECT_HEAD)&nvod_prg_item4,
	(POBJECT_HEAD)&nvod_cur_prog_bmp,
};
OBJLIST nvod_ref_event_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {70, 132, 356, 150},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = nvod_list_keymap, .pfnCallback = nvod_ref_event_list_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_ref_event_con
	},
	.pListField = nvod_ref_event_ol_ListField,
	.scrollBar = &nvod_prg_scb,
	.bListStyle = LIST_VER | LIST_NO_SLECT | LIST_ITEMS_NOCOMPLETE | LIST_SCROLL | LIST_GRID | LIST_FOCUS_FIRST | LIST_PAGE_KEEP_CURITEM | LIST_FULL_PAGE,
	.wDep = 5, .wCount = 6,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//nvod_prg_item0 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_prg_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {70, 132, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_prg_item1, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_prg_idx0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_prg_idx0 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_idx0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 132, 100, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_name0, .pRoot = (POBJECT_HEAD)&nvod_prg_item0
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15] 
};

//nvod_prg_name0 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_name0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {170, 132, 234, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_prg_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16]
};

//nvod_prg_item1 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_prg_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {70, 162, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_prg_item2, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_prg_idx1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_prg_idx1 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 162, 100, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_name1, .pRoot = (POBJECT_HEAD)&nvod_prg_item1
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17] 
};

//nvod_prg_name1 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {170, 162, 234, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_prg_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[18]
};

//nvod_prg_item2 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_prg_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {70, 192, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_prg_item3, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_prg_idx2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_prg_idx2 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 192, 100, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_name2, .pRoot = (POBJECT_HEAD)&nvod_prg_item2
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[19] 
};

//nvod_prg_name2 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {170, 192, 234, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_prg_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[20]
};

//nvod_prg_item3 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_prg_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 4, .bRightID = 4, .bUpID = 4, .bDownID = 4,
		.frame = {70, 222, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_prg_item4, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_prg_idx3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_prg_idx3 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 222, 100, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_name3, .pRoot = (POBJECT_HEAD)&nvod_prg_item3
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[21] 
};

//nvod_prg_name3 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {170, 222, 234, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_prg_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[22]
};

//nvod_prg_item4 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_prg_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 5, .bRightID = 5, .bUpID = 5, .bDownID = 5,
		.frame = {70, 252, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_cur_prog_bmp, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_prg_idx4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_prg_idx4 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 252, 100, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_name4, .pRoot = (POBJECT_HEAD)&nvod_prg_item4
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[23] 
};

//nvod_prg_name4 ------------------------------------------------------------------------

TEXT_FIELD nvod_prg_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {170, 252, 234, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_prg_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[24]
};

//nvod_cur_prog_bmp ------------------------------------------------------------------------

BITMAP nvod_cur_prog_bmp = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 132, 18, 18},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_prg_scb, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = IM_EPG_COLORBUTTON_RED,
};

//nvod_prg_scb ------------------------------------------------------------------------

SCROLL_BAR nvod_prg_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {414, 132, 12, 150},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_ref_event_ol
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 5,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 130},
	.nMax = 100, .nPos = 1
};

//nvod_sch_title ------------------------------------------------------------------------

CONTAINER nvod_sch_title = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 1,
		.frame = {66, 292, 364, 192},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_ol, .pRoot = (POBJECT_HEAD)&g_win_nvod
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_title_date,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_title_date ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_title_date = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 296, 70, 24},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_title_time, .pRoot = (POBJECT_HEAD)&nvod_sch_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = RS_HELP_DATE,
	.pString = NULL
};

//nvod_sch_title_time ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_title_time = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {140, 296, 140, 24},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_title_status, .pRoot = (POBJECT_HEAD)&nvod_sch_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = RS_SYSTEM_TIME,
	.pString = NULL
};

//nvod_sch_title_status ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_title_status = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {280, 296, 124, 24},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wStringID = RS_STATUS,
	.pString = NULL
};

//nvod_sch_ol ------------------------------------------------------------------------
static VACTION nvod_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD nvod_sch_ol_ListField[] = {
	(POBJECT_HEAD)&nvod_sch_item0,
	(POBJECT_HEAD)&nvod_sch_item1,
	(POBJECT_HEAD)&nvod_sch_item2,
	(POBJECT_HEAD)&nvod_sch_item3,
	(POBJECT_HEAD)&nvod_sch_item4,
};
OBJLIST nvod_sch_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {70, 326, 358, 150},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = nvod_list_keymap, .pfnCallback = nvod_sch_list_callback,
		.pNext = (POBJECT_HEAD)&nvod_ref_event_detail, .pRoot = (POBJECT_HEAD)&g_win_nvod
	},
	.pListField = nvod_sch_ol_ListField,
	.scrollBar = &nvod_sch_scb,
	.bListStyle = LIST_VER | LIST_NO_SLECT | LIST_ITEMS_NOCOMPLETE | LIST_SCROLL | LIST_GRID | LIST_FOCUS_FIRST | LIST_PAGE_KEEP_CURITEM | LIST_FULL_PAGE,
	.wDep = 5, .wCount = 10,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//nvod_sch_scb ------------------------------------------------------------------------

SCROLL_BAR nvod_sch_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {416, 336, 12, 150},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_item0, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 5,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 130},
	.nMax = 100, .nPos = 1
};

//nvod_sch_item0 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_sch_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {70, 326, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_sch_item1, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_date0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_date0 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_date0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {74, 326, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_time0, .pRoot = (POBJECT_HEAD)&nvod_sch_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//nvod_sch_time0 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_time0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {144, 326, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_book_bmp0, .pRoot = (POBJECT_HEAD)&nvod_sch_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//nvod_book_bmp0 ------------------------------------------------------------------------

BITMAP nvod_book_bmp0 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {284, 326, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_status0, .pRoot = (POBJECT_HEAD)&nvod_sch_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = 0,
};

//nvod_sch_status0 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_status0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {284, 326, 124, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2]
};

//nvod_sch_item1 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_sch_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {70, 356, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_sch_item2, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_date1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_date1 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_date1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {74, 356, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_time1, .pRoot = (POBJECT_HEAD)&nvod_sch_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3]
};

//nvod_sch_time1 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_time1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {144, 356, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_book_bmp1, .pRoot = (POBJECT_HEAD)&nvod_sch_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4]
};

//nvod_book_bmp1 ------------------------------------------------------------------------

BITMAP nvod_book_bmp1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {284, 356, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_status1, .pRoot = (POBJECT_HEAD)&nvod_sch_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = 0,
};

//nvod_sch_status1 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_status1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {284, 356, 124, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5]
};

//nvod_sch_item2 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_sch_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {70, 386, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_sch_item3, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_date2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_date2 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_date2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {74, 386, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_time2, .pRoot = (POBJECT_HEAD)&nvod_sch_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6]
};

//nvod_sch_time2 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_time2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {144, 386, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_book_bmp2, .pRoot = (POBJECT_HEAD)&nvod_sch_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7]
};

//nvod_book_bmp2 ------------------------------------------------------------------------

BITMAP nvod_book_bmp2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {284, 386, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_status2, .pRoot = (POBJECT_HEAD)&nvod_sch_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = 0,
};

//nvod_sch_status2 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_status2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {284, 386, 124, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8]
};

//nvod_sch_item3 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_sch_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 4, .bRightID = 4, .bUpID = 4, .bDownID = 4,
		.frame = {70, 416, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&nvod_sch_item4, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_date3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_date3 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_date3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {74, 416, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_time3, .pRoot = (POBJECT_HEAD)&nvod_sch_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9]
};

//nvod_sch_time3 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_time3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {144, 416, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_book_bmp3, .pRoot = (POBJECT_HEAD)&nvod_sch_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10]
};

//nvod_book_bmp3 ------------------------------------------------------------------------

BITMAP nvod_book_bmp3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {284, 416, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_status3, .pRoot = (POBJECT_HEAD)&nvod_sch_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = 0,
};

//nvod_sch_status3 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_status3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {284, 416, 124, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11]
};

//nvod_sch_item4 ------------------------------------------------------------------------
static VACTION nvod_sch_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_sch_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER nvod_sch_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 5, .bRightID = 5, .bUpID = 5, .bDownID = 5,
		.frame = {70, 446, 346, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_1, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = nvod_sch_list_item_con_keymap, .pfnCallback = nvod_sch_list_item_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&nvod_sch_date4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//nvod_sch_date4 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_date4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {74, 446, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_time4, .pRoot = (POBJECT_HEAD)&nvod_sch_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12]
};

//nvod_sch_time4 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_time4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {144, 446, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_book_bmp4, .pRoot = (POBJECT_HEAD)&nvod_sch_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13]
};

//nvod_book_bmp4 ------------------------------------------------------------------------

BITMAP nvod_book_bmp4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {284, 446, 70, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_sch_status4, .pRoot = (POBJECT_HEAD)&nvod_sch_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 10, .bY = 0,
	.wIconID = 0,
};

//nvod_sch_status4 ------------------------------------------------------------------------

TEXT_FIELD nvod_sch_status4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {284, 446, 124, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&nvod_sch_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14]
};

//nvod_ref_event_detail ------------------------------------------------------------------------
static VACTION nvod_detail_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT nvod_detail_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

TEXT_CONTENT nvod_ref_event_detail_text_content[] = {
	{STRING_UNICODE, 0},
};
MULTI_TEXT nvod_ref_event_detail = {
	.head = {
		.bType = OT_MULTITEXT,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {436, 292, 234, 192},
		.style = {
			.bShowIdx = WSTL_TXT_NVOD_DETAIL, .bHLIdx = WSTL_TXT_NVOD_DETAIL, .bSelIdx = WSTL_TXT_NVOD_DETAIL, .bGrayIdx = WSTL_TXT_NVOD_DETAIL
		},
		.pfnKeyMap = nvod_detail_keymap, .pfnCallback = nvod_detail_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_nvod
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_TOP,
	.bCount = 1,
	.nLine = 0,
	.rcText = {4, 4, 226, 182},
	.scrollBar = NULL,
	.pTextTable = nvod_ref_event_detail_text_content
};

//nvod_time_remain ------------------------------------------------------------------------

TEXT_FIELD nvod_time_remain = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {72, 60, 94, 24},
		.style = {
			.bShowIdx = WSTL_TXT_17, .bHLIdx = WSTL_TXT_17, .bSelIdx = WSTL_TXT_17, .bGrayIdx = WSTL_TXT_17
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_mute_bmp, .pRoot = (POBJECT_HEAD)NULL
	},
	.bAlign = C_ALIGN_RIGHT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[32]
};

//nvod_mute_bmp ------------------------------------------------------------------------

BITMAP nvod_mute_bmp = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {580, 68, 40, 40},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&nvod_help_info, .pRoot = (POBJECT_HEAD)NULL
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_MUTE,
};

//nvod_help_info ------------------------------------------------------------------------

TEXT_FIELD nvod_help_info = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 112, 358, 24},
		.style = {
			.bShowIdx = WSTL_TXT_14, .bHLIdx = WSTL_TXT_14, .bSelIdx = WSTL_TXT_14, .bGrayIdx = WSTL_TXT_14
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[25]
};
#endif//__WIN_NVOD_OBJ_H__68611DFF_18FD_44DD_9E61_87DE5EF90142
