/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_GAMES_VEGA_H__AC0942E2_830E_4A84_9F60_8F2E6D01A6EC
#define __WIN_GAMES_VEGA_H__AC0942E2_830E_4A84_9F60_8F2E6D01A6EC


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD txt_game_item1;
extern TEXT_FIELD txt_sm_game_title;
extern CONTAINER con_game_sub_menu;
extern CONTAINER g_win_games;
extern TEXT_FIELD txt_game_item2;

//g_win_games ------------------------------------------------------------------------
static VACTION game_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT game_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_games = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_SEARCH_BG_CON, .bHLIdx = WSTL_SEARCH_BG_CON, .bSelIdx = WSTL_SEARCH_BG_CON, .bGrayIdx = WSTL_SEARCH_BG_CON
		},
		.pfnKeyMap = game_keymap, .pfnCallback = game_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&con_game_sub_menu,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//con_game_sub_menu ------------------------------------------------------------------------
static VACTION game_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT game_item_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER con_game_sub_menu = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {356, 102, 314, 364},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = game_item_keymap, .pfnCallback = game_item_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_games
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_sm_game_title,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//txt_sm_game_title ------------------------------------------------------------------------

TEXT_FIELD txt_sm_game_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {360, 106, 304, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_game_item1, .pRoot = (POBJECT_HEAD)&con_game_sub_menu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_GAMES_WORLD,
	.pString = NULL
};

//txt_game_item1 ------------------------------------------------------------------------

TEXT_FIELD txt_game_item1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 2,
		.frame = {360, 166, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_game_item2, .pRoot = (POBJECT_HEAD)&con_game_sub_menu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_GAME_OTHELLO,
	.pString = NULL
};

//txt_game_item2 ------------------------------------------------------------------------

TEXT_FIELD txt_game_item2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 1,
		.frame = {360, 226, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&con_game_sub_menu
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_GAME_BOX,
	.pString = NULL
};
#endif//__WIN_GAMES_VEGA_H__AC0942E2_830E_4A84_9F60_8F2E6D01A6EC
