/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_SIGNAL_TEST_OBJ_H__6D0E521E_DDF4_4370_9E55_BDB3FF088D76
#define __WIN_SIGNAL_TEST_OBJ_H__6D0E521E_DDF4_4370_9E55_BDB3FF088D76


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER g_win_signal_test;
extern TEXT_FIELD signal_test_txt;
extern TEXT_FIELD signal_test_name2;
extern TEXT_FIELD signal_test_brief4;
extern TEXT_FIELD signal_test_time4;
extern TEXT_FIELD signal_test_name1;
extern TEXT_FIELD signal_test_name4;
extern CONTAINER signal_test_item2;
extern TEXT_FIELD signal_test_idx2;
extern TEXT_FIELD signal_test_brief1;
extern CONTAINER signal_test_ol_con;
extern TEXT_FIELD signal_test_time0;
extern TEXT_FIELD signal_test_idx1;
extern CONTAINER signal_test_item4;
extern TEXT_FIELD signal_test_name0;
extern TEXT_FIELD signal_test_brief3;
extern TEXT_FIELD signal_test_brief2;
extern TEXT_FIELD signal_test_name3;
extern TEXT_FIELD signal_test_time3;
extern TEXT_FIELD signal_test_idx3;
extern CONTAINER signal_test_item3;
extern TEXT_FIELD signal_test_idx0;
extern TEXT_FIELD signal_test_brief0;
extern TEXT_FIELD signal_test_time2;
extern SCROLL_BAR signal_test_scb;
extern TEXT_FIELD signal_test_time1;
extern CONTAINER signal_test_item0;
extern CONTAINER signal_test_item1;
extern OBJLIST signal_test_ol;
extern TEXT_FIELD signal_test_idx4;

//g_win_signal_test ------------------------------------------------------------------------
static VACTION signal_test_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT signal_test_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_signal_test = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_COMMON_BACK_2, .bHLIdx = WSTL_COMMON_BACK_2, .bSelIdx = WSTL_COMMON_BACK_2, .bGrayIdx = WSTL_COMMON_BACK_2
		},
		.pfnKeyMap = signal_test_keymap, .pfnCallback = signal_test_callback,
		.pNext = (POBJECT_HEAD)&signal_test_txt, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_ol_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//signal_test_ol_con ------------------------------------------------------------------------

CONTAINER signal_test_ol_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {66, 102, 604, 200},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_signal_test
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_ol,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//signal_test_ol ------------------------------------------------------------------------
static VACTION signal_test_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT signal_test_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD signal_test_ol_ListField[] = {
	(POBJECT_HEAD)&signal_test_item0,
	(POBJECT_HEAD)&signal_test_item1,
	(POBJECT_HEAD)&signal_test_item2,
	(POBJECT_HEAD)&signal_test_item3,
	(POBJECT_HEAD)&signal_test_item4,
};
OBJLIST signal_test_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {66, 136, 604, 166},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = signal_test_list_keymap, .pfnCallback = signal_test_list_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_ol_con
	},
	.pListField = signal_test_ol_ListField,
	.scrollBar = &signal_test_scb,
	.bListStyle = LIST_VER | LIST_SINGLE_SLECT | LIST_ITEMS_NOCOMPLETE | LIST_SCROLL | LIST_GRID | LIST_FOCUS_FIRST | LIST_PAGE_KEEP_CURITEM | LIST_FULL_PAGE,
	.wDep = 5, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//signal_test_scb ------------------------------------------------------------------------

SCROLL_BAR signal_test_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {650, 136, 12, 150},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_item0, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.bStyle = BAR_VERT_AUTO | SBAR_STYLE_RECT_STYLE,
	.bPage = 10,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 130},
	.nMax = 100, .nPos = 1
};

//signal_test_item0 ------------------------------------------------------------------------

CONTAINER signal_test_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {70, 136, 580, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_item1, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_idx0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//signal_test_idx0 ------------------------------------------------------------------------

TEXT_FIELD signal_test_idx0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 136, 80, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_time0, .pRoot = (POBJECT_HEAD)&signal_test_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//signal_test_time0 ------------------------------------------------------------------------

TEXT_FIELD signal_test_time0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {150, 136, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_name0, .pRoot = (POBJECT_HEAD)&signal_test_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5]
};

//signal_test_name0 ------------------------------------------------------------------------

TEXT_FIELD signal_test_name0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {290, 136, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_brief0, .pRoot = (POBJECT_HEAD)&signal_test_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10]
};

//signal_test_brief0 ------------------------------------------------------------------------

TEXT_FIELD signal_test_brief0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {430, 136, 220, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15]
};

//signal_test_item1 ------------------------------------------------------------------------

CONTAINER signal_test_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 2, .bDownID = 2,
		.frame = {70, 166, 580, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_item2, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_idx1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//signal_test_idx1 ------------------------------------------------------------------------

TEXT_FIELD signal_test_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 166, 80, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_time1, .pRoot = (POBJECT_HEAD)&signal_test_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//signal_test_time1 ------------------------------------------------------------------------

TEXT_FIELD signal_test_time1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {150, 166, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_name1, .pRoot = (POBJECT_HEAD)&signal_test_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6]
};

//signal_test_name1 ------------------------------------------------------------------------

TEXT_FIELD signal_test_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {290, 166, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_brief1, .pRoot = (POBJECT_HEAD)&signal_test_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11]
};

//signal_test_brief1 ------------------------------------------------------------------------

TEXT_FIELD signal_test_brief1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {430, 166, 220, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16]
};

//signal_test_item2 ------------------------------------------------------------------------

CONTAINER signal_test_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {70, 196, 580, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_item3, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_idx2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//signal_test_idx2 ------------------------------------------------------------------------

TEXT_FIELD signal_test_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 196, 80, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_time2, .pRoot = (POBJECT_HEAD)&signal_test_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2]
};

//signal_test_time2 ------------------------------------------------------------------------

TEXT_FIELD signal_test_time2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {150, 196, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_name2, .pRoot = (POBJECT_HEAD)&signal_test_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7]
};

//signal_test_name2 ------------------------------------------------------------------------

TEXT_FIELD signal_test_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {290, 196, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_brief2, .pRoot = (POBJECT_HEAD)&signal_test_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12]
};

//signal_test_brief2 ------------------------------------------------------------------------

TEXT_FIELD signal_test_brief2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {430, 196, 220, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17]
};

//signal_test_item3 ------------------------------------------------------------------------

CONTAINER signal_test_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 4, .bRightID = 4, .bUpID = 4, .bDownID = 4,
		.frame = {70, 226, 580, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_item4, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_idx3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//signal_test_idx3 ------------------------------------------------------------------------

TEXT_FIELD signal_test_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 226, 80, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_time3, .pRoot = (POBJECT_HEAD)&signal_test_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3]
};

//signal_test_time3 ------------------------------------------------------------------------

TEXT_FIELD signal_test_time3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {150, 226, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_name3, .pRoot = (POBJECT_HEAD)&signal_test_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8]
};

//signal_test_name3 ------------------------------------------------------------------------

TEXT_FIELD signal_test_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {290, 226, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_brief3, .pRoot = (POBJECT_HEAD)&signal_test_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13]
};

//signal_test_brief3 ------------------------------------------------------------------------

TEXT_FIELD signal_test_brief3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {430, 226, 220, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[18]
};

//signal_test_item4 ------------------------------------------------------------------------

CONTAINER signal_test_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 5, .bRightID = 5, .bUpID = 5, .bDownID = 5,
		.frame = {70, 256, 580, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&signal_test_idx4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//signal_test_idx4 ------------------------------------------------------------------------

TEXT_FIELD signal_test_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {70, 256, 80, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_time4, .pRoot = (POBJECT_HEAD)&signal_test_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4]
};

//signal_test_time4 ------------------------------------------------------------------------

TEXT_FIELD signal_test_time4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {150, 256, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_name4, .pRoot = (POBJECT_HEAD)&signal_test_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9]
};

//signal_test_name4 ------------------------------------------------------------------------

TEXT_FIELD signal_test_name4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {290, 256, 140, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&signal_test_brief4, .pRoot = (POBJECT_HEAD)&signal_test_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14]
};

//signal_test_brief4 ------------------------------------------------------------------------

TEXT_FIELD signal_test_brief4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {430, 256, 220, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&signal_test_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[19]
};

//signal_test_txt ------------------------------------------------------------------------

TEXT_FIELD signal_test_txt = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 0, 0},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SEARIAL_NUM,
	.pString = NULL
};
#endif//__WIN_SIGNAL_TEST_OBJ_H__6D0E521E_DDF4_4370_9E55_BDB3FF088D76
