/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_PWD_SET_OBJ_H__353BA3AA_7C8C_4D70_9430_30D8644251CD
#define __WIN_PWD_SET_OBJ_H__353BA3AA_7C8C_4D70_9430_30D8644251CD


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER win_pwd_con;
extern TEXT_FIELD par_item_txtname4;
extern TEXT_FIELD pwdset_title_name;
extern TEXT_FIELD par_item_txtset3;
extern CONTAINER par_item_con4;
extern TEXT_FIELD pwdset_msg;
extern TEXT_FIELD pwdset_back;
extern TEXT_FIELD par_item_txtset4;
extern CONTAINER g_win_pwd;
extern CONTAINER pwdset_help;
extern TEXT_FIELD par_item_txtname3;
extern CONTAINER par_item_con3;
extern TEXT_FIELD pwdset_exit;

//g_win_pwd ------------------------------------------------------------------------
static VACTION par_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT par_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_pwd = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 719, 576},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = par_con_keymap, .pfnCallback = par_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&win_pwd_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//win_pwd_con ------------------------------------------------------------------------
static VACTION pwdset_con_keymap(POBJECT_HEAD pObj, UINT32 key);

CONTAINER win_pwd_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {284, 100, 384, 300},
		.style = {
			.bShowIdx = WSTL_RCI_COM_MENU_BG, .bHLIdx = WSTL_RCI_COM_MENU_BG, .bSelIdx = WSTL_RCI_COM_MENU_BG, .bGrayIdx = WSTL_RCI_COM_MENU_BG
		},
		.pfnKeyMap = pwdset_con_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_pwd
	},
	.pNextInCntn = (POBJECT_HEAD)&par_item_con3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//par_item_con3 ------------------------------------------------------------------------
static VACTION par_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT par_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER par_item_con3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 2,
		.frame = {304, 175, 345, 30},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = par_item_con_keymap, .pfnCallback = par_item_con_callback,
		.pNext = (POBJECT_HEAD)&par_item_con4, .pRoot = (POBJECT_HEAD)&win_pwd_con
	},
	.pNextInCntn = (POBJECT_HEAD)&par_item_txtname3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//par_item_txtname3 ------------------------------------------------------------------------

TEXT_FIELD par_item_txtname3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {304, 177, 158, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&par_item_txtset3, .pRoot = (POBJECT_HEAD)&par_item_con3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_SYSTME_PARENTAL_LOCK_NEW_PASSWORD,
	.pString = NULL
};

//par_item_txtset3 ------------------------------------------------------------------------

TEXT_FIELD par_item_txtset3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {462, 177, 181, 29},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&par_item_con3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//par_item_con4 ------------------------------------------------------------------------
static VACTION par_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT par_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER par_item_con4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 1,
		.frame = {304, 229, 345, 30},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = par_item_con_keymap, .pfnCallback = par_item_con_callback,
		.pNext = (POBJECT_HEAD)&pwdset_help, .pRoot = (POBJECT_HEAD)&win_pwd_con
	},
	.pNextInCntn = (POBJECT_HEAD)&par_item_txtname4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//par_item_txtname4 ------------------------------------------------------------------------

TEXT_FIELD par_item_txtname4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {304, 232, 158, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&par_item_txtset4, .pRoot = (POBJECT_HEAD)&par_item_con4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_SYSTME_PARENTAL_LOCK_CONFIRM_PASSWORD,
	.pString = NULL
};

//par_item_txtset4 ------------------------------------------------------------------------

TEXT_FIELD par_item_txtset4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {462, 232, 179, 29},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&par_item_con4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//pwdset_help ------------------------------------------------------------------------

CONTAINER pwdset_help = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {361, 345, 203, 41},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&pwdset_title_name, .pRoot = (POBJECT_HEAD)&win_pwd_con
	},
	.pNextInCntn = (POBJECT_HEAD)&pwdset_back,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//pwdset_back ------------------------------------------------------------------------

TEXT_FIELD pwdset_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {492, 352, 66, 33},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&pwdset_exit, .pRoot = (POBJECT_HEAD)&pwdset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};

//pwdset_exit ------------------------------------------------------------------------

TEXT_FIELD pwdset_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {380, 352, 112, 33},
		.style = {
			.bShowIdx = WSTL_RCI_BLUE_ITEM, .bHLIdx = WSTL_RCI_BLUE_ITEM, .bSelIdx = WSTL_RCI_BLUE_ITEM, .bGrayIdx = WSTL_RCI_BLUE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&pwdset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//pwdset_title_name ------------------------------------------------------------------------

TEXT_FIELD pwdset_title_name = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {325, 106, 119, 24},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&pwdset_msg, .pRoot = (POBJECT_HEAD)&win_pwd_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_MODIFY_PWD,
	.pString = NULL
};

//pwdset_msg ------------------------------------------------------------------------

TEXT_FIELD pwdset_msg = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {309, 271, 326, 63},
		.style = {
			.bShowIdx = WSTL_RCI_TXT1, .bHLIdx = WSTL_RCI_TXT1, .bSelIdx = WSTL_RCI_TXT1, .bGrayIdx = WSTL_RCI_TXT1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&win_pwd_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_EMPTY,
	.pString = NULL
};
#endif//__WIN_PWD_SET_OBJ_H__353BA3AA_7C8C_4D70_9430_30D8644251CD
