/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_FREQSET_VEGA_H__DE3A0E66_6295_4ADC_9129_991B78D7167D
#define __WIN_FREQSET_VEGA_H__DE3A0E66_6295_4ADC_9129_991B78D7167D


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER g_win_freqset;
extern EDIT_FIELD txt_mf_item_value2;
extern CONTAINER main_freq_con_item2;
extern TEXT_FIELD txt_mf_item_name1;
extern TEXT_FIELD txt_mf_item_name2;
extern TEXT_FIELD freqset_comfire;
extern TEXT_FIELD freqset_exit;
extern EDIT_FIELD txt_mf_item_value1;
extern TEXT_FIELD freqset_back;
extern CONTAINER main_freq_con_item3;
extern CONTAINER main_freq_con_items;
extern CONTAINER main_freq_con_item1;
extern TEXT_FIELD freqset_modify;
extern CONTAINER freqset_help;
extern TEXT_FIELD main_freq_title;
extern MULTISEL txt_mf_item_value3;
extern TEXT_FIELD txt_mf_item_name3;

//g_win_freqset ------------------------------------------------------------------------
static VACTION win_common_item_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_main_freq_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_freqset = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 0, 720, 576},
		.style = {
			.bShowIdx = WSTL_RCI_BACKGROUND, .bHLIdx = WSTL_RCI_BACKGROUND, .bSelIdx = WSTL_RCI_BACKGROUND, .bGrayIdx = WSTL_RCI_BACKGROUND
		},
		.pfnKeyMap = win_common_item_keymap, .pfnCallback = win_main_freq_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&main_freq_con_items,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_freq_con_items ------------------------------------------------------------------------
static VACTION con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER main_freq_con_items = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {286, 110, 384, 300},
		.style = {
			.bShowIdx = WSTL_RCI_COM_MENU_BG, .bHLIdx = WSTL_RCI_COM_MENU_BG, .bSelIdx = WSTL_RCI_COM_MENU_BG, .bGrayIdx = WSTL_RCI_COM_MENU_BG
		},
		.pfnKeyMap = con_keymap, .pfnCallback = con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_freqset
	},
	.pNextInCntn = (POBJECT_HEAD)&main_freq_title,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//main_freq_title ------------------------------------------------------------------------

TEXT_FIELD main_freq_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {328, 115, 119, 24},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item1, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY_SETTINGS,
	.pString = NULL
};

//main_freq_con_item1 ------------------------------------------------------------------------

CONTAINER main_freq_con_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 3, .bDownID = 2,
		.frame = {295, 169, 345, 30},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item2, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name1 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 166, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value1, .pRoot = (POBJECT_HEAD)&main_freq_con_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_FREQUENCY,
	.pString = NULL
};

//txt_mf_item_value1 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mf_item_value1_pattern[] = "f32";
static const UINT8 txt_mf_item_value1_Suffix[] = {0, 77, 0, 72, 0, 122, 0, 0}; //Suffix = MHz
EDIT_FIELD txt_mf_item_value1 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {468, 166, 154, 29},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mf_item_value1_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[20],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mf_item_value1_Suffix,
	.valbak = 0
};

//main_freq_con_item2 ------------------------------------------------------------------------

CONTAINER main_freq_con_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 2, .bRightID = 2, .bUpID = 1, .bDownID = 3,
		.frame = {295, 219, 345, 30},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&main_freq_con_item3, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name2 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 219, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value2, .pRoot = (POBJECT_HEAD)&main_freq_con_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SEARCH_COD_SYMBOL,
	.pString = NULL
};

//txt_mf_item_value2 ------------------------------------------------------------------------
static VACTION main_freq_item_edit_keymap(POBJECT_HEAD pObj, UINT32 key);

static char txt_mf_item_value2_pattern[] = "s5";
static const UINT8 txt_mf_item_value2_Suffix[] = {0, 75, 0, 66, 0, 97, 0, 117, 0, 100, 0, 0}; //Suffix = KBaud
EDIT_FIELD txt_mf_item_value2 = {
	.head = {
		.bType = OT_EDITFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 1, .bDownID = 1,
		.frame = {468, 219, 154, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_RCI_COM_SEL_SEL, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_edit_keymap, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bMaxLen = 10,
	.pcsPattern = txt_mf_item_value2_pattern,
	.bStyle = NORMAL_EDIT_MODE,
	.bCursorMode = CURSOR_NORMAL, .bCursor = 0,
	.pString = display_strs[21],
	.pPrefix = (UINT16*)NULL, .pSuffix = (UINT16*)txt_mf_item_value2_Suffix,
	.valbak = 0
};

//main_freq_con_item3 ------------------------------------------------------------------------

CONTAINER main_freq_con_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 2, .bDownID = 1,
		.frame = {295, 269, 345, 30},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&freqset_help, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&txt_mf_item_name3,
	.FocusObjectID = 3,
	.bHiliteAsWhole = 1,
};

//txt_mf_item_name3 ------------------------------------------------------------------------

TEXT_FIELD txt_mf_item_name3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {311, 271, 157, 29},
		.style = {
			.bShowIdx = WSTL_RCI_COM_SEL_NAME_BG, .bHLIdx = WSTL_RCI_COM_SEL_NAME_BG, .bSelIdx = WSTL_RCI_COM_SEL_NAME_BG, .bGrayIdx = WSTL_RCI_COM_SEL_NAME_BG
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mf_item_value3, .pRoot = (POBJECT_HEAD)&main_freq_con_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CONSTELLATION_QAM,
	.pString = NULL
};

//txt_mf_item_value3 ------------------------------------------------------------------------
static VACTION main_freq_item_sel_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT main_freq_item_sel_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static UINT16 txt_mf_item_value3_seltable[] = {
	RS_CONSTELLATION_16,
	RS_CONSTELLATION_32,
	RS_CONSTELLATION_64,
	RS_CONSTELLATION_128,
	RS_CONSTELLATION_256,
};
MULTISEL txt_mf_item_value3 = {
	.head = {
		.bType = OT_MULTISEL,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 3, .bRightID = 3, .bUpID = 3, .bDownID = 3,
		.frame = {468, 271, 154, 30},
		.style = {
			.bShowIdx = WSTL_COM_SEL_BG, .bHLIdx = WSTL_COM_SEL_ARROW, .bSelIdx = WSTL_COM_SEL_BG, .bGrayIdx = WSTL_COM_SEL_BG
		},
		.pfnKeyMap = main_freq_item_sel_keymap, .pfnCallback = main_freq_item_sel_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.bSelType = STRING_ID,
	.pSelTable = txt_mf_item_value3_seltable,
	.nCount = 5,
	.nSel = 0,
};

//freqset_help ------------------------------------------------------------------------

CONTAINER freqset_help = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {327, 341, 309, 48},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&main_freq_con_items
	},
	.pNextInCntn = (POBJECT_HEAD)&freqset_comfire,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//freqset_comfire ------------------------------------------------------------------------

TEXT_FIELD freqset_comfire = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {314, 343, 104, 31},
		.style = {
			.bShowIdx = WSTL_RCI_YELLOW_ITEM, .bHLIdx = WSTL_RCI_YELLOW_ITEM, .bSelIdx = WSTL_RCI_YELLOW_ITEM, .bGrayIdx = WSTL_RCI_YELLOW_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&freqset_modify, .pRoot = (POBJECT_HEAD)&freqset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_BUTTON_CONFIRM,
	.pString = NULL
};

//freqset_modify ------------------------------------------------------------------------

TEXT_FIELD freqset_modify = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {418, 343, 66, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&freqset_exit, .pRoot = (POBJECT_HEAD)&freqset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_CHANGE,
	.pString = NULL
};

//freqset_exit ------------------------------------------------------------------------

TEXT_FIELD freqset_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {484, 343, 78, 31},
		.style = {
			.bShowIdx = WSTL_RCI_BLUE_ITEM, .bHLIdx = WSTL_RCI_BLUE_ITEM, .bSelIdx = WSTL_RCI_BLUE_ITEM, .bGrayIdx = WSTL_RCI_BLUE_ITEM
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&freqset_back, .pRoot = (POBJECT_HEAD)&freqset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//freqset_back ------------------------------------------------------------------------

TEXT_FIELD freqset_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 343, 73, 31},
		.style = {
			.bShowIdx = WSTL_RCI_IGNORE, .bHLIdx = WSTL_RCI_IGNORE, .bSelIdx = WSTL_RCI_IGNORE, .bGrayIdx = WSTL_RCI_IGNORE
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&freqset_help
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};
#endif//__WIN_FREQSET_VEGA_H__DE3A0E66_6295_4ADC_9129_991B78D7167D
