/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_MAIL_H__7A5DBF40_E575_4F7F_97CF_1B2C72B55144
#define __WIN_MAIL_H__7A5DBF40_E575_4F7F_97CF_1B2C72B55144


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD mail_flag3;
extern TEXT_FIELD mail_new;
extern TEXT_FIELD mail_idx5;
extern CONTAINER mail_ol_con;
extern BITMAP mail_del4;
extern TEXT_FIELD mail_title1;
extern TEXT_FIELD mail_back;
extern TEXT_FIELD mail_exit;
extern TEXT_FIELD mail_title4;
extern CONTAINER mail_item0;
extern TEXT_FIELD mail_idx4;
extern BITMAP mail_y;
extern CONTAINER mail_item2;
extern TEXT_FIELD mail_deltle;
extern BITMAP mail_del1;
extern TEXT_FIELD mail_title3;
extern CONTAINER mail_item3;
extern BITMAP mail_red;
extern BITMAP mail_del5;
extern TEXT_FIELD mail_enter;
extern SCROLL_BAR mail_scb;
extern BITMAP mail_title_txt0;
extern CONTAINER mail_con_title;
extern BITMAP mail_del2;
extern TEXT_FIELD mail_flag5;
extern TEXT_FIELD mail_title_txt3;
extern TEXT_FIELD mail_total;
extern TEXT_FIELD txt_mail_title;
extern TEXT_FIELD mail_read;
extern BITMAP bmap_mail_title;
extern TEXT_FIELD mail_idx3;
extern BITMAP mail_del3;
extern TEXT_FIELD mail_idx1;
extern CONTAINER mail_item5;
extern TEXT_FIELD mail_idx2;
extern TEXT_FIELD mail_flag0;
extern BITMAP mail_del0;
extern TEXT_FIELD mail_flag4;
extern OBJLIST mail_ol;
extern CONTAINER g_win_mail;
extern TEXT_FIELD mail_deltle_all;
extern CONTAINER mail_item4;
extern TEXT_FIELD mail_title0;
extern TEXT_FIELD mail_flag1;
extern CONTAINER mail_item1;
extern TEXT_FIELD mail_title_txt1;
extern TEXT_FIELD mail_flag2;
extern TEXT_FIELD mail_title5;
extern TEXT_FIELD mail_title2;
extern TEXT_FIELD mail_idx0;
extern TEXT_FIELD mail_title_txt2;

//g_win_mail ------------------------------------------------------------------------
static VACTION mail_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mail_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_mail = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {7, 1, 713, 575},
		.style = {
			.bShowIdx = WSTL_TRANS_IX, .bHLIdx = WSTL_TRANS_IX, .bSelIdx = WSTL_TRANS_IX, .bGrayIdx = WSTL_TRANS_IX
		},
		.pfnKeyMap = mail_keymap, .pfnCallback = mail_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_ol_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//mail_ol_con ------------------------------------------------------------------------

CONTAINER mail_ol_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 67, 584, 404},
		.style = {
			.bShowIdx = WSTL_EMIAL_OL_CON, .bHLIdx = WSTL_EMIAL_OL_CON, .bSelIdx = WSTL_EMIAL_OL_CON, .bGrayIdx = WSTL_EMIAL_OL_CON
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&bmap_mail_title, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_ol,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//mail_ol ------------------------------------------------------------------------
static VACTION mail_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT mail_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD mail_ol_ListField[] = {
	(POBJECT_HEAD)&mail_item0,
	(POBJECT_HEAD)&mail_item1,
	(POBJECT_HEAD)&mail_item2,
	(POBJECT_HEAD)&mail_item3,
	(POBJECT_HEAD)&mail_item4,
	(POBJECT_HEAD)&mail_item5,
};
OBJLIST mail_ol = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 0, .bDownID = 0,
		.frame = {104, 186, 547, 213},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_OL_LIST, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = mail_list_keymap, .pfnCallback = mail_list_callback,
		.pNext = (POBJECT_HEAD)&mail_con_title, .pRoot = (POBJECT_HEAD)&mail_ol_con
	},
	.pListField = mail_ol_ListField,
	.scrollBar = &mail_scb,
	.bListStyle = LIST_VER|LIST_NO_SLECT|LIST_NOKEEP_FOUCS|LIST_NOKEEP_SELECT|LIST_ITEMS_NOCOMPLETE|LIST_SCROLL|LIST_GRID|LIST_SELECT_FIRST|LIST_PAGE_KEEP_CURITEM|LIST_FULL_PAGE|LIST_BARSCROLL_NOCOMPLETE,
	.wDep = 6, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//mail_scb ------------------------------------------------------------------------

SCROLL_BAR mail_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {637, 158, 12, 235},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item0, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 6,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 10, 12, 50},
	.nMax = 100, .nPos = 1
};

//mail_item0 ------------------------------------------------------------------------

CONTAINER mail_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 2,
		.frame = {113, 191, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item1, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx0 ------------------------------------------------------------------------

TEXT_FIELD mail_idx0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 191, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title0, .pRoot = (POBJECT_HEAD)&mail_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//mail_title0 ------------------------------------------------------------------------

TEXT_FIELD mail_title0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 191, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag0, .pRoot = (POBJECT_HEAD)&mail_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//mail_flag0 ------------------------------------------------------------------------

TEXT_FIELD mail_flag0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 191, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del0, .pRoot = (POBJECT_HEAD)&mail_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2]
};

//mail_del0 ------------------------------------------------------------------------

BITMAP mail_del0 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 191, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_item1 ------------------------------------------------------------------------

CONTAINER mail_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {113, 226, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item2, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx1 ------------------------------------------------------------------------

TEXT_FIELD mail_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 226, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title1, .pRoot = (POBJECT_HEAD)&mail_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3]
};

//mail_title1 ------------------------------------------------------------------------

TEXT_FIELD mail_title1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 226, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag1, .pRoot = (POBJECT_HEAD)&mail_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4]
};

//mail_flag1 ------------------------------------------------------------------------

TEXT_FIELD mail_flag1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 226, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del1, .pRoot = (POBJECT_HEAD)&mail_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5]
};

//mail_del1 ------------------------------------------------------------------------

BITMAP mail_del1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 226, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_item2 ------------------------------------------------------------------------

CONTAINER mail_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {113, 262, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item3, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx2 ------------------------------------------------------------------------

TEXT_FIELD mail_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 262, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title2, .pRoot = (POBJECT_HEAD)&mail_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6]
};

//mail_title2 ------------------------------------------------------------------------

TEXT_FIELD mail_title2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 262, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag2, .pRoot = (POBJECT_HEAD)&mail_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7]
};

//mail_flag2 ------------------------------------------------------------------------

TEXT_FIELD mail_flag2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 262, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del2, .pRoot = (POBJECT_HEAD)&mail_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8]
};

//mail_del2 ------------------------------------------------------------------------

BITMAP mail_del2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 262, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_item3 ------------------------------------------------------------------------

CONTAINER mail_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {113, 297, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item4, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx3 ------------------------------------------------------------------------

TEXT_FIELD mail_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 297, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title3, .pRoot = (POBJECT_HEAD)&mail_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9]
};

//mail_title3 ------------------------------------------------------------------------

TEXT_FIELD mail_title3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 297, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag3, .pRoot = (POBJECT_HEAD)&mail_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10]
};

//mail_flag3 ------------------------------------------------------------------------

TEXT_FIELD mail_flag3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 297, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del3, .pRoot = (POBJECT_HEAD)&mail_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11]
};

//mail_del3 ------------------------------------------------------------------------

BITMAP mail_del3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 297, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_item4 ------------------------------------------------------------------------

CONTAINER mail_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {113, 333, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_item5, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx4 ------------------------------------------------------------------------

TEXT_FIELD mail_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 333, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title4, .pRoot = (POBJECT_HEAD)&mail_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12]
};

//mail_title4 ------------------------------------------------------------------------

TEXT_FIELD mail_title4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 333, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag4, .pRoot = (POBJECT_HEAD)&mail_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13]
};

//mail_flag4 ------------------------------------------------------------------------

TEXT_FIELD mail_flag4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 333, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del4, .pRoot = (POBJECT_HEAD)&mail_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14]
};

//mail_del4 ------------------------------------------------------------------------

BITMAP mail_del4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 333, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_item5 ------------------------------------------------------------------------

CONTAINER mail_item5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 1,
		.frame = {113, 367, 522, 32},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_ol
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_idx5,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//mail_idx5 ------------------------------------------------------------------------

TEXT_FIELD mail_idx5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 367, 38, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title5, .pRoot = (POBJECT_HEAD)&mail_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15]
};

//mail_title5 ------------------------------------------------------------------------

TEXT_FIELD mail_title5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 367, 280, 32},
		.style = {
			.bShowIdx = WSTL_LIST, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST, .bGrayIdx = WSTL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_flag5, .pRoot = (POBJECT_HEAD)&mail_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16]
};

//mail_flag5 ------------------------------------------------------------------------

TEXT_FIELD mail_flag5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 367, 115, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_del5, .pRoot = (POBJECT_HEAD)&mail_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17]
};

//mail_del5 ------------------------------------------------------------------------

BITMAP mail_del5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 367, 73, 32},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = 0,
};

//mail_con_title ------------------------------------------------------------------------

CONTAINER mail_con_title = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {104, 154, 532, 33},
		.style = {
			.bShowIdx = WSTL_OL_LIST, .bHLIdx = WSTL_OL_LIST, .bSelIdx = WSTL_OL_LIST, .bGrayIdx = WSTL_OL_LIST
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_ol_con
	},
	.pNextInCntn = (POBJECT_HEAD)&mail_title_txt0,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//mail_title_txt0 ------------------------------------------------------------------------

BITMAP mail_title_txt0 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {113, 158, 38, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title_txt1, .pRoot = (POBJECT_HEAD)&mail_con_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_SMALL_MAIL_CLOSE_ICON,
};

//mail_title_txt1 ------------------------------------------------------------------------

TEXT_FIELD mail_title_txt1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {156, 158, 280, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_LIST01, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title_txt2, .pRoot = (POBJECT_HEAD)&mail_con_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_TITLE,
	.pString = NULL
};

//mail_title_txt2 ------------------------------------------------------------------------

TEXT_FIELD mail_title_txt2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {440, 158, 115, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_BUTTON_3, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_title_txt3, .pRoot = (POBJECT_HEAD)&mail_con_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SYSTEM_TIME,
	.pString = NULL
};

//mail_title_txt3 ------------------------------------------------------------------------

TEXT_FIELD mail_title_txt3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {562, 158, 73, 27},
		.style = {
			.bShowIdx = WSTL_LIST01, .bHLIdx = WSTL_LIST01, .bSelIdx = WSTL_LIST01, .bGrayIdx = WSTL_LIST01
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&mail_con_title
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_DEL,
	.pString = NULL
};

//bmap_mail_title ------------------------------------------------------------------------

BITMAP bmap_mail_title = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {108, 67, 33, 29},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&txt_mail_title, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TITILE_ICON,
};

//txt_mail_title ------------------------------------------------------------------------

TEXT_FIELD txt_mail_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {142, 66, 102, 30},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_new, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_EMAIL,
	.pString = NULL
};

//mail_new ------------------------------------------------------------------------

TEXT_FIELD mail_new = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {173, 109, 132, 22},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_total, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = NULL
};

//mail_total ------------------------------------------------------------------------

TEXT_FIELD mail_total = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {336, 109, 242, 22},
		.style = {
			.bShowIdx = WSTL_TXT_5, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_5, .bGrayIdx = WSTL_TXT_5
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_enter, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = NULL
};

//mail_enter ------------------------------------------------------------------------

TEXT_FIELD mail_enter = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {78, 432, 104, 31},
		.style = {
			.bShowIdx = WSTL_MAIL_ENTER, .bHLIdx = WSTL_HIGHT_EMIAL, .bSelIdx = WSTL_MAIL_ENTER, .bGrayIdx = WSTL_MAIL_ENTER
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_read, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_BUTTON_CONFIRM,
	.pString = NULL
};

//mail_read ------------------------------------------------------------------------

TEXT_FIELD mail_read = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {184, 431, 52, 33},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_red, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_READ,
	.pString = NULL
};

//mail_red ------------------------------------------------------------------------

BITMAP mail_red = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {242, 432, 26, 24},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_deltle, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_HELP_RED,
};

//mail_deltle ------------------------------------------------------------------------

TEXT_FIELD mail_deltle = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {270, 431, 68, 33},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_y, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_DEL,
	.pString = NULL
};

//mail_y ------------------------------------------------------------------------

BITMAP mail_y = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {342, 432, 26, 24},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_deltle_all, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_HELP_YELLOW,
};

//mail_deltle_all ------------------------------------------------------------------------

TEXT_FIELD mail_deltle_all = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {369, 431, 96, 33},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_exit, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_DELETE_ALL,
	.pString = NULL
};

//mail_exit ------------------------------------------------------------------------

TEXT_FIELD mail_exit = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {469, 432, 61, 31},
		.style = {
			.bShowIdx = WSTL_HIGHT_EMIAL, .bHLIdx = WSTL_HIGHT_EMIAL, .bSelIdx = WSTL_HIGHT_EMIAL, .bGrayIdx = WSTL_HIGHT_EMIAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&mail_back, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_EXIT,
	.pString = NULL
};

//mail_back ------------------------------------------------------------------------

TEXT_FIELD mail_back = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {536, 431, 56, 33},
		.style = {
			.bShowIdx = WSTL_TXT_3, .bHLIdx = WSTL_TXT_3, .bSelIdx = WSTL_TXT_3, .bGrayIdx = WSTL_TXT_3
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_mail
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_HELP_BACK,
	.pString = NULL
};
#endif//__WIN_MAIL_H__7A5DBF40_E575_4F7F_97CF_1B2C72B55144
