/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_CA_SERVICENTITLE_H__563FD175_6CE7_47BA_B5CC_B23F021E824C
#define __WIN_CA_SERVICENTITLE_H__563FD175_6CE7_47BA_B5CC_B23F021E824C


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern CONTAINER service_entitle_item2;
extern TEXT_FIELD service_entitle_exp1;
extern CONTAINER service_entitle_item0;
extern TEXT_FIELD service_entitle_rcd1;
extern TEXT_FIELD service_entitle_op0;
extern TEXT_FIELD service_entitle_op3;
extern TEXT_FIELD service_entitle_rcd4;
extern TEXT_FIELD service_entitle_idx4;
extern TEXT_FIELD service_entitle_table_title_expire;
extern CONTAINER service_entitle_item7;
extern SCROLL_BAR service_entitle_scb;
extern CONTAINER service_entitle_title_con;
extern TEXT_FIELD service_entitle_op8;
extern TEXT_FIELD service_entitle_idx1;
extern TEXT_FIELD service_entitle_op2;
extern TEXT_FIELD service_entitle_rcd0;
extern CONTAINER service_entitle_item1;
extern CONTAINER g_win_service_entitle;
extern OBJLIST service_entitle_olist;
extern CONTAINER service_entitle_con;
extern TEXT_FIELD service_entitle_exp5;
extern TEXT_FIELD service_entitle_op4;
extern TEXT_FIELD service_entitle_table_title_op;
extern TEXT_FIELD service_entitle_op7;
extern TEXT_FIELD service_entitle_exp8;
extern TEXT_FIELD service_entitle_idx5;
extern TEXT_FIELD service_entitle_exp3;
extern TEXT_FIELD service_entitle_idx8;
extern CONTAINER service_entitle_item8;
extern TEXT_FIELD service_entitle_idx2;
extern TEXT_FIELD service_entitle_rcd7;
extern TEXT_FIELD service_entitle_rcd2;
extern TEXT_FIELD service_entitle_exp7;
extern TEXT_FIELD service_entitle_exp2;
extern TEXT_FIELD service_entitle_idx0;
extern CONTAINER service_entitle_item5;
extern TEXT_FIELD service_entitle_rcd8;
extern CONTAINER service_entitle_item4;
extern CONTAINER service_entitle_item6;
extern TEXT_FIELD service_entitle_exp4;
extern TEXT_FIELD service_entitle_op6;
extern TEXT_FIELD service_entitle_op5;
extern TEXT_FIELD service_entitle_rcd6;
extern TEXT_FIELD service_entitle_rcd5;
extern TEXT_FIELD service_entitle_exp6;
extern CONTAINER service_entitle_item3;
extern TEXT_FIELD service_entitle_op1;
extern TEXT_FIELD service_entitle_idx7;
extern TEXT_FIELD service_entitle_table_title_id;
extern TEXT_FIELD service_entitle_idx6;
extern TEXT_FIELD service_entitle_rcd3;
extern TEXT_FIELD service_entitle_idx3;
extern TEXT_FIELD service_entitle_exp0;
extern TEXT_FIELD service_entitle_table_title_record;

//g_win_service_entitle ------------------------------------------------------------------------
static VACTION service_entitle_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_service_entitle = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_COMMON_BACK_2, .bHLIdx = WSTL_COMMON_BACK_2, .bSelIdx = WSTL_COMMON_BACK_2, .bGrayIdx = WSTL_COMMON_BACK_2
		},
		.pfnKeyMap = service_entitle_keymap, .pfnCallback = service_entitle_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//service_entitle_con ------------------------------------------------------------------------

CONTAINER service_entitle_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {47, 102, 620, 370},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_olist, .pRoot = (POBJECT_HEAD)&g_win_service_entitle
	},
	.pNextInCntn = (POBJECT_HEAD)NULL,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//service_entitle_olist ------------------------------------------------------------------------
static VACTION service_entitle_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD service_entitle_olist_ListField[] = {
	(POBJECT_HEAD)&service_entitle_item0,
	(POBJECT_HEAD)&service_entitle_item1,
	(POBJECT_HEAD)&service_entitle_item2,
	(POBJECT_HEAD)&service_entitle_item3,
	(POBJECT_HEAD)&service_entitle_item4,
	(POBJECT_HEAD)&service_entitle_item5,
	(POBJECT_HEAD)&service_entitle_item6,
	(POBJECT_HEAD)&service_entitle_item7,
	(POBJECT_HEAD)&service_entitle_item8,
};
OBJLIST service_entitle_olist = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 0, .bDownID = 0,
		.frame = {66, 140, 566, 274},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = service_entitle_list_keymap, .pfnCallback = service_entitle_list_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_title_con, .pRoot = (POBJECT_HEAD)&g_win_service_entitle
	},
	.pListField = service_entitle_olist_ListField,
	.scrollBar = &service_entitle_scb,
	.bListStyle = LIST_VER|LIST_NO_SLECT|LIST_NOKEEP_FOUCS|LIST_NOKEEP_SELECT|LIST_ITEMS_NOCOMPLETE|LIST_SCROLL|LIST_GRID|LIST_SELECT_FIRST|LIST_PAGE_KEEP_CURITEM|LIST_FULL_PAGE|LIST_BARSCROLL_NOCOMPLETE,
	.wDep = 9, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//service_entitle_scb ------------------------------------------------------------------------

SCROLL_BAR service_entitle_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {637, 140, 19, 268},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_item0, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 9,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 14, 15, 240},
	.nMax = 100, .nPos = 0
};

//service_entitle_item0 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 9, .bDownID = 2,
		.frame = {69, 140, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item1, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op0 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 140, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx0, .pRoot = (POBJECT_HEAD)&service_entitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//service_entitle_idx0 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 140, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd0, .pRoot = (POBJECT_HEAD)&service_entitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//service_entitle_rcd0 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 140, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp0, .pRoot = (POBJECT_HEAD)&service_entitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2]
};

//service_entitle_exp0 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 140, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3]
};

//service_entitle_item1 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {69, 172, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item2, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op1 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 172, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx1, .pRoot = (POBJECT_HEAD)&service_entitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4]
};

//service_entitle_idx1 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 172, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd1, .pRoot = (POBJECT_HEAD)&service_entitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5]
};

//service_entitle_rcd1 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 172, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp1, .pRoot = (POBJECT_HEAD)&service_entitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6]
};

//service_entitle_exp1 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 172, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7]
};

//service_entitle_item2 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {69, 204, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item3, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op2 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 204, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx2, .pRoot = (POBJECT_HEAD)&service_entitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8]
};

//service_entitle_idx2 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 204, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd2, .pRoot = (POBJECT_HEAD)&service_entitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[9]
};

//service_entitle_rcd2 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 204, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp2, .pRoot = (POBJECT_HEAD)&service_entitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[10]
};

//service_entitle_exp2 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 204, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[11]
};

//service_entitle_item3 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {69, 236, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item4, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op3 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 236, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx3, .pRoot = (POBJECT_HEAD)&service_entitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[12]
};

//service_entitle_idx3 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 236, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd3, .pRoot = (POBJECT_HEAD)&service_entitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[13]
};

//service_entitle_rcd3 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 236, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp3, .pRoot = (POBJECT_HEAD)&service_entitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[14]
};

//service_entitle_exp3 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 236, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[15]
};

//service_entitle_item4 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {69, 268, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item5, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op4 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 268, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx4, .pRoot = (POBJECT_HEAD)&service_entitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[16]
};

//service_entitle_idx4 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 268, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd4, .pRoot = (POBJECT_HEAD)&service_entitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[17]
};

//service_entitle_rcd4 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 268, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp4, .pRoot = (POBJECT_HEAD)&service_entitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[18]
};

//service_entitle_exp4 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 268, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[19]
};

//service_entitle_item5 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 7,
		.frame = {69, 300, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item6, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op5,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op5 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 300, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx5, .pRoot = (POBJECT_HEAD)&service_entitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[20]
};

//service_entitle_idx5 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 300, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd5, .pRoot = (POBJECT_HEAD)&service_entitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[21]
};

//service_entitle_rcd5 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 300, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp5, .pRoot = (POBJECT_HEAD)&service_entitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[22]
};

//service_entitle_exp5 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 300, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[23]
};

//service_entitle_item6 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item6 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 7, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 8,
		.frame = {69, 332, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item7, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op6,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op6 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 332, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx6, .pRoot = (POBJECT_HEAD)&service_entitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[24]
};

//service_entitle_idx6 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 332, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd6, .pRoot = (POBJECT_HEAD)&service_entitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[25]
};

//service_entitle_rcd6 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 332, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp6, .pRoot = (POBJECT_HEAD)&service_entitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[26]
};

//service_entitle_exp6 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 332, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[27]
};

//service_entitle_item7 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item7 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 8, .bLeftID = 0, .bRightID = 0, .bUpID = 7, .bDownID = 9,
		.frame = {69, 364, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&service_entitle_item8, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op7,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op7 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 364, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx7, .pRoot = (POBJECT_HEAD)&service_entitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[28]
};

//service_entitle_idx7 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 364, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd7, .pRoot = (POBJECT_HEAD)&service_entitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[29]
};

//service_entitle_rcd7 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 364, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp7, .pRoot = (POBJECT_HEAD)&service_entitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[30]
};

//service_entitle_exp7 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 364, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[31]
};

//service_entitle_item8 ------------------------------------------------------------------------
static VACTION service_entitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT service_entitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER service_entitle_item8 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 9, .bLeftID = 0, .bRightID = 0, .bUpID = 8, .bDownID = 1,
		.frame = {69, 396, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = service_entitle_list_item_con_keymap, .pfnCallback = service_entitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_op8,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//service_entitle_op8 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_op8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {71, 394, 118, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_idx8, .pRoot = (POBJECT_HEAD)&service_entitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[32]
};

//service_entitle_idx8 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_idx8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 394, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_rcd8, .pRoot = (POBJECT_HEAD)&service_entitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[33]
};

//service_entitle_rcd8 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_rcd8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 394, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_exp8, .pRoot = (POBJECT_HEAD)&service_entitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[34]
};

//service_entitle_exp8 ------------------------------------------------------------------------

TEXT_FIELD service_entitle_exp8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 394, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[35]
};

//service_entitle_title_con ------------------------------------------------------------------------

CONTAINER service_entitle_title_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {53, 102, 603, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_service_entitle
	},
	.pNextInCntn = (POBJECT_HEAD)&service_entitle_table_title_op,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//service_entitle_table_title_op ------------------------------------------------------------------------

TEXT_FIELD service_entitle_table_title_op = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {67, 102, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_table_title_id, .pRoot = (POBJECT_HEAD)&service_entitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_OPERATOR_ID,
	.pString = NULL
};

//service_entitle_table_title_id ------------------------------------------------------------------------

TEXT_FIELD service_entitle_table_title_id = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {189, 102, 130, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_table_title_record, .pRoot = (POBJECT_HEAD)&service_entitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_PRODUCT_ID,
	.pString = NULL
};

//service_entitle_table_title_record ------------------------------------------------------------------------

TEXT_FIELD service_entitle_table_title_record = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {319, 102, 120, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&service_entitle_table_title_expire, .pRoot = (POBJECT_HEAD)&service_entitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_RECORD_ENABLE,
	.pString = NULL
};

//service_entitle_table_title_expire ------------------------------------------------------------------------

TEXT_FIELD service_entitle_table_title_expire = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {439, 102, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&service_entitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SE_ENDTIME,
	.pString = NULL
};
#endif//__WIN_CA_SERVICENTITLE_H__563FD175_6CE7_47BA_B5CC_B23F021E824C
