/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_CA_DETITLE_H__3D6963F2_51B1_423B_929C_CBF52A2A5B9F
#define __WIN_CA_DETITLE_H__3D6963F2_51B1_423B_929C_CBF52A2A5B9F


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD detitle_status7;
extern TEXT_FIELD detitle_code2;
extern CONTAINER detitle_item1;
extern TEXT_FIELD detitle_code1;
extern CONTAINER detitle_item7;
extern CONTAINER detitle_con;
extern BITMAP ca_detitle_delete_6;
extern TEXT_FIELD detitle_status1;
extern BITMAP ca_detitle_delete_1;
extern TEXT_FIELD detitle_table_title_status1;
extern CONTAINER detitle_item8;
extern BITMAP ca_detitle_delete_2;
extern CONTAINER detitle_item3;
extern TEXT_FIELD detitle_code4;
extern TEXT_FIELD detitle_table_title_status;
extern TEXT_FIELD detitle_table_title_code;
extern BITMAP ca_detitle_delete_3;
extern TEXT_FIELD detitle_status8;
extern CONTAINER detitle_item6;
extern TEXT_FIELD detitle_code8;
extern TEXT_FIELD detitle_code0;
extern CONTAINER ca_detitle_title_con;
extern TEXT_FIELD detitle_status0;
extern BITMAP ca_detitle_delete_8;
extern CONTAINER detitle_item4;
extern BITMAP ca_detitle_delete_7;
extern SCROLL_BAR detitle_scb;
extern TEXT_FIELD detitle_code7;
extern TEXT_FIELD detitle_code3;
extern TEXT_FIELD detitle_status6;
extern OBJLIST detitle_olist;
extern TEXT_FIELD detitle_code6;
extern TEXT_FIELD detitle_status3;
extern TEXT_FIELD detitle_code5;
extern CONTAINER g_win_detitle;
extern BITMAP ca_detitle_delete_5;
extern TEXT_FIELD detitle_status5;
extern CONTAINER detitle_item5;
extern BITMAP ca_detitle_delete_4;
extern TEXT_FIELD detitle_status2;
extern BITMAP ca_detitle_delete_0;
extern CONTAINER detitle_item0;
extern TEXT_FIELD detitle_status4;
extern CONTAINER detitle_item2;

//g_win_detitle ------------------------------------------------------------------------
static VACTION win_detitle_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_detitle = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_COMMON_BACK_2, .bHLIdx = WSTL_COMMON_BACK_2, .bSelIdx = WSTL_COMMON_BACK_2, .bGrayIdx = WSTL_COMMON_BACK_2
		},
		.pfnKeyMap = win_detitle_keymap, .pfnCallback = win_detitle_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//detitle_con ------------------------------------------------------------------------

CONTAINER detitle_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {45, 102, 620, 370},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_olist, .pRoot = (POBJECT_HEAD)&g_win_detitle
	},
	.pNextInCntn = (POBJECT_HEAD)NULL,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 0,
};

//detitle_olist ------------------------------------------------------------------------
static VACTION win_detitle_list_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

static POBJECT_HEAD detitle_olist_ListField[] = {
	(POBJECT_HEAD)&detitle_item0,
	(POBJECT_HEAD)&detitle_item1,
	(POBJECT_HEAD)&detitle_item2,
	(POBJECT_HEAD)&detitle_item3,
	(POBJECT_HEAD)&detitle_item4,
	(POBJECT_HEAD)&detitle_item5,
	(POBJECT_HEAD)&detitle_item6,
	(POBJECT_HEAD)&detitle_item7,
	(POBJECT_HEAD)&detitle_item8,
};
OBJLIST detitle_olist = {
	.head = {
		.bType = OT_OBJLIST,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 1, .bRightID = 1, .bUpID = 0, .bDownID = 0,
		.frame = {64, 160, 566, 274},
		.style = {
			.bShowIdx = WSTL_NOSHOW_IDX, .bHLIdx = WSTL_NOSHOW_IDX, .bSelIdx = WSTL_NOSHOW_IDX, .bGrayIdx = WSTL_NOSHOW_IDX
		},
		.pfnKeyMap = win_detitle_list_keymap, .pfnCallback = win_detitle_list_callback,
		.pNext = (POBJECT_HEAD)&ca_detitle_title_con, .pRoot = (POBJECT_HEAD)&g_win_detitle
	},
	.pListField = detitle_olist_ListField,
	.scrollBar = &detitle_scb,
	.bListStyle = LIST_VER|LIST_NO_SLECT|LIST_NOKEEP_FOUCS|LIST_NOKEEP_SELECT|LIST_ITEMS_NOCOMPLETE|LIST_SCROLL|LIST_GRID|LIST_SELECT_FIRST|LIST_PAGE_KEEP_CURITEM|LIST_FULL_PAGE|LIST_BARSCROLL_NOCOMPLETE,
	.wDep = 9, .wCount = 0,
	.wTop = 0, .wCurPoint = 0, .wNewPoint = 0,
	.wSelect = 0, .dwSelect = NULL,
	.pSelMarkObj = NULL
};

//detitle_scb ------------------------------------------------------------------------

SCROLL_BAR detitle_scb = {
	.head = {
		.bType = OT_SCROLLBAR,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {635, 153, 19, 288},
		.style = {
			.bShowIdx = WSTL_SCROLLBAR_1, .bHLIdx = WSTL_SCROLLBAR_1, .bSelIdx = WSTL_SCROLLBAR_1, .bGrayIdx = WSTL_SCROLLBAR_1
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_item0, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.bStyle = BAR_VERT_AUTO|SBAR_STYLE_RECT_STYLE,
	.bPage = 9,
	.wThumbID = WSTL_SCROLLBAR_2, .wTickBg = WSTL_NOSHOW_IDX,
	.rcBar = {0, 14, 15, 240},
	.nMax = 100, .nPos = 0
};

//detitle_item0 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item0 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 9, .bDownID = 2,
		.frame = {67, 155, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item1, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code0,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code0 ------------------------------------------------------------------------

TEXT_FIELD detitle_code0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 155, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status0, .pRoot = (POBJECT_HEAD)&detitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[0]
};

//detitle_status0 ------------------------------------------------------------------------

TEXT_FIELD detitle_status0 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 155, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_0, .pRoot = (POBJECT_HEAD)&detitle_item0
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_0 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_0 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {507, 155, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item0
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item1 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item1 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {67, 185, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item2, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code1,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code1 ------------------------------------------------------------------------

TEXT_FIELD detitle_code1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 185, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status1, .pRoot = (POBJECT_HEAD)&detitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[1]
};

//detitle_status1 ------------------------------------------------------------------------

TEXT_FIELD detitle_status1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 185, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_1, .pRoot = (POBJECT_HEAD)&detitle_item1
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_1 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_1 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {507, 188, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item1
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item2 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item2 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {67, 215, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item3, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code2,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code2 ------------------------------------------------------------------------

TEXT_FIELD detitle_code2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 215, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status2, .pRoot = (POBJECT_HEAD)&detitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[2]
};

//detitle_status2 ------------------------------------------------------------------------

TEXT_FIELD detitle_status2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 215, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_2, .pRoot = (POBJECT_HEAD)&detitle_item2
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_2 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_2 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {506, 218, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item2
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item3 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item3 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {67, 245, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item4, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code3,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code3 ------------------------------------------------------------------------

TEXT_FIELD detitle_code3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 245, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status3, .pRoot = (POBJECT_HEAD)&detitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[3]
};

//detitle_status3 ------------------------------------------------------------------------

TEXT_FIELD detitle_status3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 245, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_3, .pRoot = (POBJECT_HEAD)&detitle_item3
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_3 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_3 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {506, 249, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item3
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item4 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item4 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {67, 275, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item5, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code4,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code4 ------------------------------------------------------------------------

TEXT_FIELD detitle_code4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 275, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status4, .pRoot = (POBJECT_HEAD)&detitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[4]
};

//detitle_status4 ------------------------------------------------------------------------

TEXT_FIELD detitle_status4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 275, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_4, .pRoot = (POBJECT_HEAD)&detitle_item4
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_4 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_4 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {506, 277, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item4
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item5 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item5 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 7,
		.frame = {67, 305, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item6, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code5,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code5 ------------------------------------------------------------------------

TEXT_FIELD detitle_code5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 305, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status5, .pRoot = (POBJECT_HEAD)&detitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[5]
};

//detitle_status5 ------------------------------------------------------------------------

TEXT_FIELD detitle_status5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 305, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_5, .pRoot = (POBJECT_HEAD)&detitle_item5
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_5 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_5 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {506, 306, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item5
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item6 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item6 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 7, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 8,
		.frame = {67, 335, 554, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item7, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code6,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code6 ------------------------------------------------------------------------

TEXT_FIELD detitle_code6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 335, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status6, .pRoot = (POBJECT_HEAD)&detitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[6]
};

//detitle_status6 ------------------------------------------------------------------------

TEXT_FIELD detitle_status6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {248, 335, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_6, .pRoot = (POBJECT_HEAD)&detitle_item6
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_6 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_6 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {505, 335, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item6
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item7 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item7 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 8, .bLeftID = 0, .bRightID = 0, .bUpID = 7, .bDownID = 9,
		.frame = {67, 365, 553, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)&detitle_item8, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code7,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code7 ------------------------------------------------------------------------

TEXT_FIELD detitle_code7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 365, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status7, .pRoot = (POBJECT_HEAD)&detitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[7]
};

//detitle_status7 ------------------------------------------------------------------------

TEXT_FIELD detitle_status7 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 365, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_7, .pRoot = (POBJECT_HEAD)&detitle_item7
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_7 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_7 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {505, 367, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item7
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//detitle_item8 ------------------------------------------------------------------------
static VACTION win_detitle_list_item_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT win_detitle_list_item_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER detitle_item8 = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 9, .bLeftID = 0, .bRightID = 0, .bUpID = 8, .bDownID = 1,
		.frame = {67, 395, 552, 30},
		.style = {
			.bShowIdx = WSTL_BUTTON_2, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_BUTTON_2, .bGrayIdx = WSTL_BUTTON_2
		},
		.pfnKeyMap = win_detitle_list_item_con_keymap, .pfnCallback = win_detitle_list_item_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_olist
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_code8,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 1,
};

//detitle_code8 ------------------------------------------------------------------------

TEXT_FIELD detitle_code8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {69, 398, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_status8, .pRoot = (POBJECT_HEAD)&detitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = 0,
	.pString = display_strs[8]
};

//detitle_status8 ------------------------------------------------------------------------

TEXT_FIELD detitle_status8 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {250, 397, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_5, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_10
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&ca_detitle_delete_8, .pRoot = (POBJECT_HEAD)&detitle_item8
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS_READED,
	.pString = NULL
};

//ca_detitle_delete_8 ------------------------------------------------------------------------

BITMAP ca_detitle_delete_8 = {
	.head = {
		.bType = OT_BITMAP,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {505, 399, 30, 27},
		.style = {
			.bShowIdx = 0, .bHLIdx = 0, .bSelIdx = 0, .bGrayIdx = 0
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&detitle_item8
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wIconID = IM_TV_DEL,
};

//ca_detitle_title_con ------------------------------------------------------------------------

CONTAINER ca_detitle_title_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {50, 104, 603, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_detitle
	},
	.pNextInCntn = (POBJECT_HEAD)&detitle_table_title_code,
	.FocusObjectID = 0,
	.bHiliteAsWhole = 1,
};

//detitle_table_title_code ------------------------------------------------------------------------

TEXT_FIELD detitle_table_title_code = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {62, 104, 183, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_table_title_status, .pRoot = (POBJECT_HEAD)&ca_detitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_CODE,
	.pString = NULL
};

//detitle_table_title_status ------------------------------------------------------------------------

TEXT_FIELD detitle_table_title_status = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {249, 104, 180, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&detitle_table_title_status1, .pRoot = (POBJECT_HEAD)&ca_detitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_DETITLE_STATUS,
	.pString = NULL
};

//detitle_table_title_status1 ------------------------------------------------------------------------

TEXT_FIELD detitle_table_title_status1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {474, 104, 121, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&ca_detitle_title_con
	},
	.bAlign = C_ALIGN_LEFT|C_ALIGN_VCENTER,
	.bX = 20, .bY = 0,
	.wStringID = RS_HELP_DELETE,
	.pString = NULL
};
#endif//__WIN_CA_DETITLE_H__3D6963F2_51B1_423B_929C_CBF52A2A5B9F
