/***************************************************************************************************
	This header file is generated by the Vega from a xform file.
	Please don't modify it!!
---------------------------------------------------------------------------------------------------*/
		
#ifndef __WIN_CA_OPERATOR_INFO_DETAIL_H__95047A9A_7561_4EF4_A0D7_1EFE6A291B35
#define __WIN_CA_OPERATOR_INFO_DETAIL_H__95047A9A_7561_4EF4_A0D7_1EFE6A291B35


/*******************************************************************************
*	Objects definition
*******************************************************************************/
extern TEXT_FIELD operator_detail_but6;
extern TEXT_FIELD operator_detail_but3;
extern CONTAINER operator_detail_con;
extern TEXT_FIELD operator_detail_but5;
extern TEXT_FIELD operator_detail_title;
extern CONTAINER g_win_operator_info_detail;
extern TEXT_FIELD operator_detail_but1;
extern TEXT_FIELD operator_detail_but4;
extern TEXT_FIELD operator_detail_but2;

//g_win_operator_info_detail ------------------------------------------------------------------------
static VACTION operator_detail_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT operator_detail_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER g_win_operator_info_detail = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {0, 90, 720, 400},
		.style = {
			.bShowIdx = WSTL_COMMON_BACK_2, .bHLIdx = WSTL_COMMON_BACK_2, .bSelIdx = WSTL_COMMON_BACK_2, .bGrayIdx = WSTL_COMMON_BACK_2
		},
		.pfnKeyMap = operator_detail_keymap, .pfnCallback = operator_detail_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)NULL
	},
	.pNextInCntn = (POBJECT_HEAD)&operator_detail_con,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//operator_detail_con ------------------------------------------------------------------------
static VACTION operator_detail_con_keymap(POBJECT_HEAD pObj, UINT32 key);
static PRESULT operator_detail_con_callback(POBJECT_HEAD pObj, VEVENT event, UINT32 param1, UINT32 param2);

CONTAINER operator_detail_con = {
	.head = {
		.bType = OT_CONTAINER,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {356, 102, 314, 364},
		.style = {
			.bShowIdx = WSTL_WIN_1, .bHLIdx = WSTL_WIN_1, .bSelIdx = WSTL_WIN_1, .bGrayIdx = WSTL_WIN_1
		},
		.pfnKeyMap = operator_detail_con_keymap, .pfnCallback = operator_detail_con_callback,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&g_win_operator_info_detail
	},
	.pNextInCntn = (POBJECT_HEAD)&operator_detail_title,
	.FocusObjectID = 1,
	.bHiliteAsWhole = 0,
};

//operator_detail_title ------------------------------------------------------------------------

TEXT_FIELD operator_detail_title = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 0, .bLeftID = 0, .bRightID = 0, .bUpID = 0, .bDownID = 0,
		.frame = {360, 106, 304, 30},
		.style = {
			.bShowIdx = WSTL_TXT_4, .bHLIdx = WSTL_TXT_4, .bSelIdx = WSTL_TXT_4, .bGrayIdx = WSTL_TXT_4
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but1, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_OPERATOR_INFORMATION,
	.pString = NULL
};

//operator_detail_but1 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but1 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 1, .bLeftID = 0, .bRightID = 0, .bUpID = 6, .bDownID = 2,
		.frame = {360, 151, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but2, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SERVICE_ENTITLES,
	.pString = NULL
};

//operator_detail_but2 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but2 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 2, .bLeftID = 0, .bRightID = 0, .bUpID = 1, .bDownID = 3,
		.frame = {360, 196, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but3, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SLOT_INFO,
	.pString = NULL
};

//operator_detail_but3 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but3 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 3, .bLeftID = 0, .bRightID = 0, .bUpID = 2, .bDownID = 4,
		.frame = {360, 241, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but4, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_IPPV_PROGRAM,
	.pString = NULL
};

//operator_detail_but4 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but4 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 4, .bLeftID = 0, .bRightID = 0, .bUpID = 3, .bDownID = 5,
		.frame = {360, 286, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but5, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_CHILD_PARENT_CARD,
	.pString = NULL
};

//operator_detail_but5 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but5 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 5, .bLeftID = 0, .bRightID = 0, .bUpID = 4, .bDownID = 6,
		.frame = {360, 331, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)&operator_detail_but6, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_DETITLE,
	.pString = NULL
};

//operator_detail_but6 ------------------------------------------------------------------------

TEXT_FIELD operator_detail_but6 = {
	.head = {
		.bType = OT_TEXTFIELD,
		.bAttr = C_ATTR_ACTIVE, .bFont = 0,
		.bID = 6, .bLeftID = 0, .bRightID = 0, .bUpID = 5, .bDownID = 1,
		.frame = {360, 376, 304, 30},
		.style = {
			.bShowIdx = WSTL_LCL_ITEM_NORMAL, .bHLIdx = WSTL_BUTTON_1, .bSelIdx = WSTL_LCL_ITEM_NORMAL, .bGrayIdx = WSTL_LCL_ITEM_NORMAL
		},
		.pfnKeyMap = NULL, .pfnCallback = NULL,
		.pNext = (POBJECT_HEAD)NULL, .pRoot = (POBJECT_HEAD)&operator_detail_con
	},
	.bAlign = C_ALIGN_CENTER|C_ALIGN_VCENTER,
	.bX = 0, .bY = 0,
	.wStringID = RS_SCINFO_AREACODE,
	.pString = NULL
};
#endif//__WIN_CA_OPERATOR_INFO_DETAIL_H__95047A9A_7561_4EF4_A0D7_1EFE6A291B35
