/***********************************************************
 *		autoconf.h
 *
 * This file is auto generated by Ali IDE. If you don't know 
 * what you are doning, please left it untouched.
***********************************************************/

#ifndef _AUTOCONF_H_
#define _AUTOCONF_H_


// Below is modules selection. 
// You can make use of them in your source code.

#define m3327 y
#define BUS y
#define BUS_DOG y
#define BUS_DOG_M33 y
#define BUS_I2C y
#define BUS_I2C_GPIO y
#define BUS_I2C_SCB y
#define BUS_SCI y
#define BUS_SCI_UART y
#define HLD y
#undef HLD_DECA
#define HLD_DECV y
#define HLD_DMX y
#define HLD_GE y
#define HLD_NIM y
#define HLD_OSD y
#define HLD_PAN y
#undef HLD_SMC
#undef HLD_SND
#define HLD_STO y
#undef HLD_VENC
#define HLD_VP y
#define LIB y
#define LIB_APPLET y
#define LIB_BOOTUPG3 y
#undef LIB_MP
#undef LIB_IMAGEDEC
#undef LIB_GIFDEC
#undef LIB_JPEGDEC
#undef LIB_PNGDEC
#define LIB_PUB y
#define LIB_PUB_ALL y
#define LIB_PUB_AS_C y
#undef LIB_PUB_AS_ENGINE
#define LIB_UPG4 y
#define LIB_UPG4_OTA y
#undef LIB_CAS
#undef CDCA
#define LIB_COMMON y
#define LIB_C y
#undef LIB_CHAR
#define LIB_ZIP y
#define LIB_7ZIP y
#define LIB_GNUZIP y
#define LIB_DVB y
#define LIB_DBC y
#undef LIB_EPG
#undef LIB_NVOD
#define LIB_SI y
#define LIB_TSI3 y
#undef LIB_TSI3_CON_PSI
#undef LIB_TSI3_DESCRIPTOR
#define LIB_TSI3_ENGINE y
#undef LIB_TSI3_PARSER
#undef LIB_TSI3_PLUGIN_EIT
#undef LIB_TSI3_PLUGIN_MONITOR
#undef LIB_TSI3_PLUGIN_SEARCH
#define LIB_TSI3_PLUGIN_TDT y
#define LIB_TSI3_UTILITY y
#undef LIBOTA_DVBC
#define LIB_LOADER y
#define LIB_STORAGE y
#define LIB_CHUNK y
#undef LIB_DATABASE
#undef LIB_DB4
#undef LIB_DB4_ENGINE
#undef LIB_DB4_INTERFACE
#undef LIB_DB4_PLUGIN_C
#define LIB_STBINFO y
#undef LIB_UI
#undef LIB_GE
#define LLD y
#define LLD_NIM y
#define LLD_NIM_C y
#undef LLD_TUN_C_RT820
#define LLD_PAN y
#define LLD_IRC y
#define LLD_IRC_M63 y
#define LLD_PAN_TP6X0 y
#undef LLD_SMC
#undef LLD_SMARTCARD
#define LLD_STO y
#define LLD_STO_FLASH y
#undef LLD_VENC
#undef LLD_VENC_M33
#undef UDI
#undef UDI_IPANEL
#define VERSION_INFO y


// Below is macros specified by modules. 
// You can make use of them in your source code.
#if m3327 ==  y
#endif /* m3327 */
#if BUS ==  y
#endif /* BUS */
#if BUS_DOG ==  y
#endif /* BUS_DOG */
#if BUS_DOG_M33 ==  y
#endif /* BUS_DOG_M33 */
#if BUS_I2C ==  y
#endif /* BUS_I2C */
#if BUS_I2C_GPIO ==  y
#endif /* BUS_I2C_GPIO */
#if BUS_I2C_SCB ==  y
#endif /* BUS_I2C_SCB */
#if BUS_SCI ==  y
#endif /* BUS_SCI */
#if BUS_SCI_UART ==  y
#endif /* BUS_SCI_UART */
#if HLD ==  y
#endif /* HLD */
#if HLD_DECA ==  y
#endif /* HLD_DECA */
#if HLD_DECV ==  y
#endif /* HLD_DECV */
#if HLD_DMX ==  y
#endif /* HLD_DMX */
#if HLD_GE ==  y
#endif /* HLD_GE */
#if HLD_NIM ==  y
#endif /* HLD_NIM */
#if HLD_OSD ==  y
#endif /* HLD_OSD */
#if HLD_PAN ==  y
#endif /* HLD_PAN */
#if HLD_SMC ==  y
#endif /* HLD_SMC */
#if HLD_SND ==  y
#endif /* HLD_SND */
#if HLD_STO ==  y
#endif /* HLD_STO */
#if HLD_VENC ==  y
#endif /* HLD_VENC */
#if HLD_VP ==  y
#endif /* HLD_VP */
#if LIB ==  y
#endif /* LIB */
#if LIB_APPLET ==  y
#endif /* LIB_APPLET */
#if LIB_BOOTUPG3 ==  y
#endif /* LIB_BOOTUPG3 */
#if LIB_MP ==  y
#endif /* LIB_MP */
#if LIB_IMAGEDEC ==  y
#endif /* LIB_IMAGEDEC */
#if LIB_GIFDEC ==  y
#endif /* LIB_GIFDEC */
#if LIB_JPEGDEC ==  y
#endif /* LIB_JPEGDEC */
#if LIB_PNGDEC ==  y
#endif /* LIB_PNGDEC */
#if LIB_PUB ==  y
#endif /* LIB_PUB */
#if LIB_PUB_ALL ==  y
#endif /* LIB_PUB_ALL */
#if LIB_PUB_AS_C ==  y
#endif /* LIB_PUB_AS_C */
#if LIB_PUB_AS_ENGINE ==  y
#endif /* LIB_PUB_AS_ENGINE */
#if LIB_UPG4 ==  y
#endif /* LIB_UPG4 */
#if LIB_UPG4_OTA ==  y
#endif /* LIB_UPG4_OTA */
#if LIB_CAS ==  y
#endif /* LIB_CAS */
#if CDCA ==  y
#endif /* CDCA */
#if LIB_COMMON ==  y
#endif /* LIB_COMMON */
#if LIB_C ==  y
#endif /* LIB_C */
#if LIB_CHAR ==  y
#endif /* LIB_CHAR */
#if LIB_ZIP ==  y
#endif /* LIB_ZIP */
#if LIB_7ZIP ==  y
#endif /* LIB_7ZIP */
#if LIB_GNUZIP ==  y
#endif /* LIB_GNUZIP */
#if LIB_DVB ==  y
#endif /* LIB_DVB */
#if LIB_DBC ==  y
#endif /* LIB_DBC */
#if LIB_EPG ==  y
#endif /* LIB_EPG */
#if LIB_NVOD ==  y
#endif /* LIB_NVOD */
#if LIB_SI ==  y
#endif /* LIB_SI */
#if LIB_TSI3 ==  y
#endif /* LIB_TSI3 */
#if LIB_TSI3_CON_PSI ==  y
#endif /* LIB_TSI3_CON_PSI */
#if LIB_TSI3_DESCRIPTOR ==  y
#endif /* LIB_TSI3_DESCRIPTOR */
#if LIB_TSI3_ENGINE ==  y
#endif /* LIB_TSI3_ENGINE */
#if LIB_TSI3_PARSER ==  y
#endif /* LIB_TSI3_PARSER */
#if LIB_TSI3_PLUGIN_EIT ==  y
#endif /* LIB_TSI3_PLUGIN_EIT */
#if LIB_TSI3_PLUGIN_MONITOR ==  y
#endif /* LIB_TSI3_PLUGIN_MONITOR */
#if LIB_TSI3_PLUGIN_SEARCH ==  y
#endif /* LIB_TSI3_PLUGIN_SEARCH */
#if LIB_TSI3_PLUGIN_TDT ==  y
#endif /* LIB_TSI3_PLUGIN_TDT */
#if LIB_TSI3_UTILITY ==  y
#endif /* LIB_TSI3_UTILITY */
#if LIBOTA_DVBC ==  y
#endif /* LIBOTA_DVBC */
#if LIB_LOADER ==  y
#endif /* LIB_LOADER */
#if LIB_STORAGE ==  y
#endif /* LIB_STORAGE */
#if LIB_CHUNK ==  y
#endif /* LIB_CHUNK */
#if LIB_DATABASE ==  y
#endif /* LIB_DATABASE */
#if LIB_DB4 ==  y
#endif /* LIB_DB4 */
#if LIB_DB4_ENGINE ==  y
#endif /* LIB_DB4_ENGINE */
#if LIB_DB4_INTERFACE ==  y
#endif /* LIB_DB4_INTERFACE */
#if LIB_DB4_PLUGIN_C ==  y
#endif /* LIB_DB4_PLUGIN_C */
#if LIB_STBINFO ==  y
#endif /* LIB_STBINFO */
#if LIB_UI ==  y
#endif /* LIB_UI */
#if LIB_GE ==  y
#endif /* LIB_GE */
#if LLD ==  y
#endif /* LLD */
#if LLD_NIM ==  y
#endif /* LLD_NIM */
#if LLD_NIM_C ==  y
#endif /* LLD_NIM_C */
#if LLD_TUN_C_RT820 ==  y
#endif /* LLD_TUN_C_RT820 */
#if LLD_PAN ==  y
#endif /* LLD_PAN */
#if LLD_IRC ==  y
#endif /* LLD_IRC */
#if LLD_IRC_M63 ==  y
#endif /* LLD_IRC_M63 */
#if LLD_PAN_TP6X0 ==  y
#endif /* LLD_PAN_TP6X0 */
#if LLD_SMC ==  y
#endif /* LLD_SMC */
#if LLD_SMARTCARD ==  y
#endif /* LLD_SMARTCARD */
#if LLD_STO ==  y
#endif /* LLD_STO */
#if LLD_STO_FLASH ==  y
#endif /* LLD_STO_FLASH */
#if LLD_VENC ==  y
#endif /* LLD_VENC */
#if LLD_VENC_M33 ==  y
#endif /* LLD_VENC_M33 */
#if UDI ==  y
#endif /* UDI */
#if UDI_IPANEL ==  y
#endif /* UDI_IPANEL */
#if VERSION_INFO ==  y
#endif /* VERSION_INFO */






#endif /* _AUTOCONF_H_ */
