#ifndef _SYSTEM_DATA_COM_H_
#define _SYSTEM_DATA_COM_H_

#include <sys_config.h>

#define TRANS_COLOR		0xFF
#define BLACK_COLOR		0xF4
#define WHITE_COLOR	0xFC
#define GRAY_COLOR		0xF9
#define YELLOW_COLOR	0x7F
#define BLUE_COLOR		0x10

typedef enum
{
	TV_MODE_AUTO = 0,
	TV_MODE_PAL,
	TV_MODE_PAL_M,//  PAL3.58
	TV_MODE_PAL_N,
	TV_MODE_NTSC358,//NTSC3.58
	TV_MODE_NTSC443,
	TV_MODE_SECAM,
	TV_MODE_576P,
	TV_MODE_480P,
	TV_MODE_720P_50,
	TV_MODE_720P_60,
	TV_MODE_1080I_25,
	TV_MODE_1080I_30,	
	TV_MODE_BY_EDID,
	TV_MODE_1080P_50,
	TV_MODE_1080P_60,	
	TV_MODE_1080P_25,
	TV_MODE_1080P_30,	
	TV_MODE_1080P_24,
} TV_MODE_TYPE;

typedef enum
{
    DISPLAY_MODE_NORMAL = 0,
    DISPLAY_MODE_LETTERBOX,
    DISPLAY_MODE_PANSCAN,
} DISPLAY_MODE_TYPE;

typedef enum
{
	TV_ASPECT_RATIO_43 = 0,
	TV_ASPECT_RATIO_169,
	TV_ASPECT_RATIO_AUTO
} TV_ASPECT_RATIO_TYPE;

typedef enum
{
	SCART_CVBS = 0,
	SCART_RGB,
#ifdef VDAC_USE_SVIDEO_TYPE
	SCART_SVIDEO,
#endif
	SCART_YUV,
} SCART_OUT_TYPE;

typedef enum
{
    ENGLISH_ENV = 0,
    CHINESE_ENV,
} LANG_GROUP_t;

#endif//_SYSTEM_DATA_COM_H_

