const WINSTYLE wSHStyle1[] __attribute__((section(".flash"))) = 
{
//WSTL_NOSHOW_IDX
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0x60, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TRANS_IX
	{C_WS_LINE_DRAW, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, C_MIXER|0x60, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_COMMON_BACK_1
	{C_WS_LINE_DRAW, 0xbe38, 0xbe38, 0xbe38, 0xbe38, 0xbe38, 0xbe38, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_COMMON_BACK_2
	{C_WS_LINE_DRAW, 0xba39, 0xba39, 0xba39, 0xba39, 0xba39, 0xba39, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_1
	{C_WS_PIC_DRAW, IM_BUTTON_01_M, IM_BUTTON_01_L, IM_BUTTON_01_R, INVALID_INDEX, C_NOSHOW, C_MIXER|0XF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_2
	{C_WS_LINE_DRAW, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_3
	{C_WS_PIC_DRAW, IM_BUTTON_01_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_4
	{C_WS_LINE_DRAW, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_5
	{C_WS_PIC_DRAW, IM_BUTTON_01_M, IM_BUTTON_01_ARROW_LEFT, IM_BUTTON_01_ARROW_RIGHT, INVALID_INDEX, C_NOSHOW, C_MIXER|0x8caa, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_6
	{C_WS_PIC_DRAW, IM_BUTTON_02_M, IM_BUTTON_02_L, IM_BUTTON_02_R, INVALID_INDEX, C_NOSHOW, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_7
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xc6da, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_8
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_SH
	{C_WS_PIC_DRAW, IM_BUTTON_POPWIN01_M, IM_BUTTON_POPWIN01_L, IM_BUTTON_POPWIN01_R, INVALID_INDEX, C_NOSHOW, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_HL
	{C_WS_PIC_DRAW, IM_BUTTON_POPWIN02_M, IM_BUTTON_POPWIN02_L, IM_BUTTON_POPWIN02_R, INVALID_INDEX, C_NOSHOW, C_MIXER|0x8caa, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_1
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xdf3c, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_2
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xe3d3, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_3
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_4
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_5
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0x8caa, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_6
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0x8caa, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_7
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xa9d7, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_8
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xbe38|C_MIXER, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_9
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xffff, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_10
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xba39, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_11
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0xa9d7, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_12
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xba39, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_13
	{C_WS_LINE_DRAW, 0xaf4a, 0xaf4a, 0xaf4a, 0xaf4a, 0xaf4a, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_14
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0x9953, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_15
	{C_WS_LINE_DRAW, 0xbe38, 0xbe38, 0xbe38, 0xbe38, 0xbe38, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_16
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|0xd2db, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_17
	{C_WS_LINE_DRAW, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, C_MIXER|0x81E1, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TXT_POPWIN
	{C_WS_LINE_DRAW, 0xd2db, 0xd2db, 0xd2db, 0xd2db, 0xd2db, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_WIN_POP
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xd2db|C_MIXER, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_TITLE
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0Xa9b5|C_MIXER, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_NVOD_DETAIL
	{C_WS_PIC_DRAW, IM_WIN_02_T, IM_WIN_02_L, IM_WIN_02_R, IM_WIN_02_B, C_MIXER|0xa9d7, C_MIXER|0xa152, IM_WIN_02_LT, IM_WIN_02_LB, IM_WIN_02_RT, IM_WIN_02_RB, LIB_ICON},
//WSTL_TXT_PREVIEW
	{C_WS_LINE_DRAW, 0, 0, 0, 0, 0, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_PROG_NAME
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_SINGAL_BAR_E_BG, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_PROG_NAME_EPG
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0x8caf, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_FINGERPRINT_1
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, 0xba39, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_FINGERPRINT_2
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, 0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MAINMENU_MAIN_CON
	{C_WS_PIC_DRAW, IM_MIDDLE_BG_01, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xba39, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_HELP_BAR_BACK
	{C_WS_PIC_DRAW, IM_MMENU_HELPWIN_M, IM_MMENU_HELPWIN_L, IM_MMENU_HELPWIN_R, INVALID_INDEX, C_MIXER, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MAINMENU_PREVIEW
	{C_WS_PIC_DRAW, IM_MMENU_TVWIN_T, IM_MMENU_TVWIN_L, IM_MMENU_TVWIN_R, IM_MMENU_TVWIN_B, 0, C_MIXER|0xd35f, IM_MMENU_TVWIN_LT, IM_MMENU_TVWIN_LB, IM_MMENU_TVWIN_RT, IM_MMENU_TVWIN_RB, LIB_ICON},
//WSTL_PREVIEW_TXT
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SCROLLBAR_1
	{C_WS_PIC_DRAW, INVALID_INDEX, IM_SCROLL_BAR_BG, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_NOSHOW, IM_SCROLL_BAR_ARROW_TOP, IM_SCROLL_BAR_ARROW_BOTTOM, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SCROLLBAR_2
	{C_WS_PIC_DRAW, INVALID_INDEX, IM_SCROLL_SCROLL_MIDDLE, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_NOSHOW, IM_SCROLL_SCROLL_TOP, IM_SCROLL_SCROLL_BOTTOM, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_WIN_1
	{C_WS_PIC_DRAW, IM_WIN_01_T, IM_WIN_01_L, IM_WIN_01_R, IM_WIN_01_B, C_MIXER|0xa9d7, C_NOSHOW, IM_WIN_01_LT, IM_WIN_01_LB, IM_WIN_01_RT, IM_WIN_01_RB, LIB_ICON},
//WSTL_WIN_2
	{C_WS_PIC_DRAW, IM_WIN_02_T, IM_WIN_02_L, IM_WIN_02_R, IM_WIN_02_B, C_MIXER|0xa9d7, C_NOSHOW, IM_WIN_02_LT, IM_WIN_02_LB, IM_WIN_02_RT, IM_WIN_02_RB, LIB_ICON},
//WSTL_TITLE_CON_IDX
	{C_WS_PIC_DRAW, IM_TITLE_BG_01, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_MIXER, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_POP_WIN_1
	{C_WS_PIC_DRAW, IM_POPWIN_01_T, IM_POPWIN_01_L, IM_POPWIN_01_R, IM_POPWIN_01_B, 0xd2db, C_NOSHOW, IM_POPWIN_01_LT, IM_POPWIN_01_LB, IM_POPWIN_01_RT, IM_POPWIN_01_RB, LIB_ICON},
//WSTL_VOLUME_01
	{C_WS_PIC_DRAW, IM_VOLUME_BG, IM_VOLUME_LEFT, IM_VOLUME_RIGHT, INVALID_INDEX, C_NOSHOW, C_MIXER|0xBF, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_BG
	{C_WS_PIC_DRAW, IM_VOLUME_BG, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_MIXER|0xBF, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_FG
	{C_WS_LINE_DRAW, 0xa152, 0xa152, 0xa152, 0xa152, 0xa152, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_CON_BG
	{C_WS_LINE_DRAW, 0x9931, 0x9931, 0x9931, 0x9931, 0x9931, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_CON_FG
	{C_WS_LINE_DRAW, 0xfbde, 0xfbde, 0xfbde, 0xfbde, 0xfbde, C_MIXER|0x9931, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_BG
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0x9931, C_MIXER|0x9931, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_BAR_TICK_FORCE
	{C_WS_PIC_DRAW, IM_VOLUME_TICK_S, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_MIXER|0xbe38, C_MIXER|0xbe38, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BARBG_01
	{C_WS_PIC_DRAW, IM_SIGNAL_GRAY_MIDDLE, IM_SIGNAL_GRAY_LEFT, IM_SIGNAL_GRAY_RIGHT, INVALID_INDEX, C_MIXER|0xc6da, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BARBG_02
	{C_WS_PIC_DRAW, IM_SIGNALBG_MIDDLE, IM_SIGNALBG_LEFT, IM_SIGNALBG_RIGHT, INVALID_INDEX, C_MIXER|0xbe38, C_MIXER|0xbe38, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_TICK_FORCE
	{wstyle_setline(C_WS_LINE_DRAW,C_SINGLE_LINE), 0xffe0, 0xffe0, 0xffe0, 0xffe0, 0xffff, C_MIXER|0xcf1b, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_HEAD_BG
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xa9d7, C_MIXER|0xa9d7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_01
	{C_WS_PIC_DRAW, IM_SIGNAL_ORANGE_MIDDLE, IM_SIGNAL_ORANGE_LEFT, IM_SIGNAL_ORANGE_RIGHT, C_NOSHOW, 0xc6da, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_02
	{C_WS_PIC_DRAW, IM_SIGNAL_GREEN_MIDDLE, IM_SIGNAL_GREEN_LEFT, IM_SIGNAL_GREEN_RIGHT, INVALID_INDEX, 0xc6da, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_03
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xc6da, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_04
	{C_WS_PIC_DRAW, IM_SIGNAL_BLUE_MIDDLE, IM_SIGNAL_BLUE_LEFT, IM_SIGNAL_BLUE_RIGHT, INVALID_INDEX, C_MIXER|0xbe38, C_MIXER|0xbe38, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_WIN_SIGNAL_01
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xd2db, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_AUDIO_WIN_01
	{C_WS_PIC_DRAW, INVALID_INDEX, IM_AUDIO_ARROW_LEFT, IM_AUDIO_ARROW_RIGHT, INVALID_INDEX, 0xa9d7, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_EPG_PREVIEW
	{C_WS_PIC_DRAW, IM_TVWIN_02_T, IM_TVWIN_02_L, IM_TVWIN_02_R, IM_TVWIN_02_B, 0, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_LIGHT_CHANNEL_LST_CON
	{C_WS_PIC_DRAW, IM_SLISTWIN_01_T, IM_SLISTWIN_01_L, IM_SLISTWIN_01_R, IM_SLISTWIN_01_B, 0xa9d7, 0xd35f, IM_SLISTWIN_01_LT, IM_SLISTWIN_01_LB, IM_SLISTWIN_01_RT, IM_SLISTWIN_01_RB, LIB_ICON},
//WSTL_LCL_ITEM_NORMAL
	{C_WS_LINE_DRAW, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, C_MIXER|0xbe97, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_ITEM_GRAY
	{C_WS_LINE_DRAW, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, 0xa9d7, C_MIXER|0xba39, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_SEARCH_BG_CON
	{C_WS_PIC_DRAW, IM_MIDDLE_BG_02, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xba39, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_PROG_NAME
	{C_WS_PIC_DRAW, IM_SINGAL_BAR_E_BG, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_NOSHOW, IM_SINGAL_BAR_E_LEFT, INVALID_INDEX, IM_SINGAL_BAR_E_RIGHT, IM_SINGAL_BAR_E_B, LIB_ICON},
//WSTL_SUBMENU_PREVIEW
	{C_WS_PIC_DRAW, IM_TVWIN_01_T, IM_TVWIN_01_L, IM_TVWIN_01_R, IM_TVWIN_01_B, 0, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TITLE_TXT_BG
	{C_WS_PIC_DRAW, IM_SLISTWIN_01_T, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW|C_MIXER, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_GAME_TETRIS_BG
	{C_WS_LINE_DRAW, 0X8000, 0X8000, 0X8000, 0X8000, 0X8000, C_MIXER, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, LIB_ICON},
//WSTL_AUDIO_LST_CON
	{C_WS_PIC_DRAW, IM_SLISTWIN_01_T, IM_SLISTWIN_01_L, IM_SLISTWIN_01_R, IM_SLISTWIN_01_B, 0xa9d7, 0xd35f, IM_SLISTWIN_02_LT, IM_SLISTWIN_01_LB, IM_SLISTWIN_02_RT, IM_SLISTWIN_01_RB, LIB_ICON},
//WSTL_INFO_CHINPUT_01
	{C_WS_PIC_DRAW, IM_NUMBER, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_MIXER|0xa152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_GRP_TITLE
	{C_WS_PIC_DRAW, IM_WIN_01_T, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_GRP_TITLE_ARROW
	{C_WS_PIC_DRAW|0x800, C_NOSHOW, IM_GROUP_LEFT, IM_GROUP_RIGHT, C_NOSHOW, C_NOSHOW|C_MIXER, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_02
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_VOLUME_BAR_TOP, INVALID_INDEX, INVALID_INDEX, IM_MEDIAPLAY_VOLUME_BAR_BOTTOM, IM_MEDIAPLAY_VOLUME_BAR_MIDDLE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_02_BG
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_MEDIAPLAY_VOLUME_BAR_MIDDLE, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_02_FG
	{C_WS_LINE_DRAW, 0xb6b9, 0xb6b9, 0xb6b9, 0xb6b9, 0xb6b9, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_INFO_03
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_WIN_MIDDLE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xB7, C_MIXER|0xA1, IM_MEDIAPLAY_WIN_LEFT, INVALID_INDEX, IM_MEDIAPLAY_WIN_RIGHT, INVALID_INDEX, LIB_ICON},
//WSTL_MP3_BAR01
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_BAR_01_MIDDLE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_BUTTON_01
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_BUTTON_01_M, IM_MEDIAPLAY_BUTTON_01_L, IM_MEDIAPLAY_BUTTON_01_R, INVALID_INDEX, 0xB0, C_MIXER|0xA0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_BUTTON_02
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_BUTTON_02_M, IM_MEDIAPLAY_BUTTON_02_L, IM_MEDIAPLAY_BUTTON_02_R, INVALID_INDEX, 0XB7, C_MIXER|0xA4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_BARBG_01
	{C_WS_PIC_DRAW, IM_MEDIAPLAY_RATEBG_01, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_MIXER|0xB0, C_MIXER|0xA4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_PREV_01
	{C_WS_LINE_DRAW, 0xbf|C_DOUBLE_LINE, 0xbf|C_DOUBLE_LINE, 0xbf|C_DOUBLE_LINE, 0xbf|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR, C_MIXER|0xA0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_PREV_02
	{C_WS_LINE_DRAW, 0xf2|C_DOUBLE_LINE, 0xf2|C_DOUBLE_LINE, 0xf2|C_DOUBLE_LINE, 0xf2|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR, C_MIXER|0xA0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_ZOOM_WIN_01
	{C_WS_LINE_DRAW, 0xb6b9, 0xb6b9, 0xb6b9, 0xb6b9, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_LINE_GAP
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xba39|C_MIXER, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_IPPV_ITEM_HI
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x10, C_NOSHOW|C_MIXER, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_INFO_CHINPUT_02
	{C_WS_PIC_DRAW, IM_NUMBER_RADIO, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, C_MIXER|0xA152, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_FREEPREVIEWING_TXT
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x0, C_MIXER|0xFE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_S_NORMAL
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_MIXER|0xa9d7, C_MIXER|0xd35f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MAINMENU_PREV_BG
	{C_WS_PIC_DRAW, IM_PREV_TOP_NEW, IM_PREV_LEFT, IM_PREV_RIGHT, IM_PREV_BOTTOM, 0, C_MIXER|0xd35f, IM_PREV_TOP, IM_PREV_BOTTOM_LEFT, IM_PREV_TOP_RIGHT, IM_PREV_BOTTOM_RIGHT, LIB_ICON},
//WSTL_NOSHOW_EXT
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0, C_MIXER|0XD35F, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SEL_ITEM_SH
	{C_WS_PIC_DRAW, IM_SEL_ITEM_SH_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, IM_SEL_ITEM_SH_L, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SEL_ITEM_HL
	{C_WS_PIC_DRAW, IM_SEL_ITEM_HL_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, IM_SEL_ITEM_HL_L, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_LIST_BG
	{C_WS_LINE_DRAW, 0XE35D, 0XE35D, 0XE35D, 0XE35D, 0xe35d, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SEL_ITEM_TITLE
	{C_WS_PIC_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_SEL_ITEM_ENTRY_MENU_TITLE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_WIN_EPG
	{wstyle_setline(C_WS_LINE_DRAW,C_SINGLE_LINE), INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xeb9e, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_TITILE
	{C_WS_PIC_DRAW, IM_EPG_MENU_TITLE_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EPG_MENU_TITLE_L, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_DATE
	{C_WS_PIC_DRAW, IM_EPG_DATE_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EPG_DATE_L, INVALID_INDEX, IM_EPG_DATE_R, INVALID_INDEX, LIB_ICON},
//WSTL_MY_PROG_ITEM
	{C_WS_PIC_DRAW, IM_EPG_SRH_ITEM_SH, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_PROG_HL
	{C_WS_PIC_DRAW, IM_EPG_PROG_ITEM_HL_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, IM_EPG_PROG_ITEM_HL_L, INVALID_INDEX, IM_EPG_PROG_ITEM_HL_R, INVALID_INDEX, LIB_ICON},
//WSTL_EPG_MY_ITEM
	{C_WS_PIC_DRAW, INVALID_INDEX, IM_EPG_PROG_ITEM_SH, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_HL
	{C_WS_PIC_DRAW, IM_EPG_CH_ITEM_HL_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EPG_CH_ITEM_HL_L, INVALID_INDEX, IM_EPG_CH_ITEM_HL_R, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_MENU
	{C_WS_PIC_DRAW, INVALID_INDEX, IM_EPG_MENU_BG_L, INVALID_INDEX, INVALID_INDEX, 0xeb9e, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_EPG_HELP
	{C_WS_PIC_DRAW, IM_EPG_HELP_BG_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EPG_HELP_BG_L, INVALID_INDEX, IM_EPG_HELP_BG_R, INVALID_INDEX, LIB_ICON},
//WSTL_YELLO_ITEM
	{C_WS_PIC_DRAW, IM_YELLOW_ITEM_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_YELLOW_ITEM_L, INVALID_INDEX, IM_YELLOW_ITEM_R, INVALID_INDEX, LIB_ICON},
//WSTL_BULE_ITEM
	{C_WS_PIC_DRAW, IM_BLUE_ITEM_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_BLUE_ITEM_L, INVALID_INDEX, IM_BLUE_ITEM_R, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_BACKGROUND
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_LAST_WIN_BG
	{C_WS_PIC_DRAW, IM_LAST_WIN_BG_T, IM_LAST_WIN_BG_L, IM_LAST_WIN_BG_R, IM_LAST_WIN_BG_B, 0xe35d, C_NOSHOW, IM_LAST_WIN_BG_L_T, IM_LAST_WIN_BG_L_B, IM_LAST_WIN_BG_R_T, IM_LAST_WIN_BG_R_B, LIB_ICON},
//WSTL_RCI_COM_TITLE
	{C_WS_PIC_DRAW, IM_COM_TITLE_M, IM_COM_TITLE_L, IM_COM_TITLE_R, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, LIB_ICON},
//WSTL_RCI_IGNORE
	{wstyle_setline(C_WS_LINE_DRAW,C_SINGLE_LINE), C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_C_GRAY
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xe35d, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_TXT_2
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x810f, 0xffff, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_TXT_1
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xbe78, 0xffff, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_WHITE_FRAME
	{C_WS_PIC_DRAW, IM_WHITE_FRAME_T, IM_WHITE_FRAME_L, IM_WHITE_FRAME_R, IM_WHITE_FRAME_B, 0xefdf, 0x8000, IM_WHITE_FRAME_L_T, IM_WHITE_FRAME_L_B, IM_WHITE_FRAME_R_T, IM_WHITE_FRAME_R_B, LIB_ICON},
//WSTL_RCI_COM_TITLE_BG
	{C_WS_PIC_DRAW, IM_COM_TITLE_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, C_NOSHOW, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_TRANSPARENT
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x5150, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_COM_SEL_NAME_BG
	{C_WS_PIC_DRAW, IM_COM_SEL_NAME_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0X8000, IM_COM_SEL_NAME_L, C_NOSHOW, IM_COM_SEL_NAME_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_COM_SEL_SEL_BG
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_BG_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_COM_SEL_SEL_BG_L, C_NOSHOW, IM_COM_SEL_SEL_BG_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_COM_SEL_SEL
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_COM_SEL_SEL_L, C_NOSHOW, IM_COM_SEL_SEL_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_COM_MENU_BG
	{C_WS_PIC_DRAW, IM_COM_MENU_BG_M, IM_COM_MENU_BG_L, IM_COM_MENU_BG_R, IM_COM_MENU_BG_B, 0xe35d, C_NOSHOW, IM_COM_MENU_BG_LT, IM_COM_MENU_BG_LB, IM_COM_MENU_BG_RT, IM_COM_MENU_BG_RB, LIB_ICON},
//WSTL_RCI_BLUE_ITEM
	{C_WS_PIC_DRAW, IM_BLUE_ITEM_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_BLUE_ITEM_L, C_NOSHOW, IM_BLUE_ITEM_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_YELLOW_ITEM
	{C_WS_PIC_DRAW, IM_YELLOW_ITEM_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_YELLOW_ITEM_L, C_NOSHOW, IM_YELLOW_ITEM_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_WHITE
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xefdf, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_BLACK_BG
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_EMIAL_MAIN_CONT
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x5150, 0xfeab, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_EMIAL_OL_CON
	{C_WS_PIC_DRAW, IM_COM_MENU_BG_M, IM_COM_MENU_BG_L, IM_COM_MENU_BG_R, IM_COM_MENU_BG_B, 0xe35d, INVALID_INDEX, IM_COM_MENU_BG_LT, IM_COM_MENU_BG_LB, IM_COM_MENU_BG_RT, IM_COM_MENU_BG_RB, LIB_ICON},
//WSTL_MAIL_ENTER
	{C_WS_PIC_DRAW, IM_YELLOW_ITEM_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_YELLOW_ITEM_L, INVALID_INDEX, IM_YELLOW_ITEM_R, INVALID_INDEX, LIB_ICON},
//WSTL_HIGHT_EMIAL
	{C_WS_PIC_DRAW, IM_BLUE_ITEM_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_BLUE_ITEM_L, INVALID_INDEX, IM_BLUE_ITEM_R, INVALID_INDEX, LIB_ICON},
//WSTL_OL_LIST
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xefdf, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_LIST
	{C_WS_PIC_DRAW, IM_EMAIL_LIST_ITEM_01_SH_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EMAIL_LIST_ITEM_01_SH_L, INVALID_INDEX, IM_EMAIL_LIST_ITEM_01_SH_R, INVALID_INDEX, LIB_ICON},
//WSTL_LIST01
	{C_WS_PIC_DRAW, IM_EMAIL_LIST_ITEM_02_SH_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_EMAIL_LIST_ITEM_02_SH_L, INVALID_INDEX, IM_EMAIL_LIST_ITEM_02_SH_R, INVALID_INDEX, LIB_ICON},
//WSTL_COM_SEL_BG
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_BG_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, INVALID_INDEX, INVALID_INDEX, IM_COM_SEL_SEL_BG_R, INVALID_INDEX, LIB_ICON},
//WSTL_COM_SEL_ARROW
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_BG_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, IM_SEL_ARROW_L, INVALID_INDEX, IM_SEL_ARROW_R, INVALID_INDEX, LIB_ICON},
//WSTL_BULE_FRAME_CON
	{C_WS_PIC_DRAW, IM_BLUE_FRAME_T, IM_BLUE_FRAME_L, IM_BLUE_FRAME_R, IM_BLUE_FRAME_B, 0xb2ff, 0x8000, IM_BLUE_FRAME_L_T, IM_BLUE_FRAME_L_B, IM_BLUE_FRAME_R_T, IM_BLUE_FRAME_R_B, LIB_ICON},
//WSTL_TXT_BULE_BG
	{wstyle_setline(C_WS_LINE_DRAW,C_SINGLE_LINE), INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xb2ff, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_COM_SEL_SEL_ARROW
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_BG_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_COM_SEL_ARROW_L, C_NOSHOW, IM_COM_SEL_ARROW_R, C_NOSHOW, LIB_ICON},
//WSTL_YU_WHITE_FRAME
	{C_WS_PIC_DRAW, IM_WHITE_FRAME_T, IM_WHITE_FRAME_L, IM_WHITE_FRAME_R, IM_WHITE_FRAME_B, 0xefdf, INVALID_INDEX, IM_WHITE_FRAME_L_T, IM_WHITE_FRAME_L_B, IM_WHITE_FRAME_R_T, IM_WHITE_FRAME_R_B, LIB_ICON},
//WSTL_YU_COM_SEL_NAME
	{C_WS_PIC_DRAW, IM_COM_SEL_NAME_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, IM_COM_SEL_NAME_L, INVALID_INDEX, IM_COM_SEL_NAME_R, INVALID_INDEX, LIB_ICON},
//WSTL_YU_SEL
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_BG_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, INVALID_INDEX, INVALID_INDEX, IM_COM_SEL_SEL_BG_R, INVALID_INDEX, LIB_ICON},
//WSTL_YU_WHITE
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xefdf, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_YU_ORANGE
	{wstyle_setline(C_WS_LINE_DRAW,C_SINGLE_LINE), 0x8000, 0x8000, 0x8000, 0x8000, 0xfa80, INVALID_INDEX, 0x8000, 0x8000, 0x8000, 0x8000, LIB_ICON},
//WSTL_YU_BLUE
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xaedf, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_YU_JINDUTIAO
	{C_WS_LINE_DRAW, 0x8000, 0x8000, 0x8000, 0x8000, 0xefdf, INVALID_INDEX, 0x8000, 0x8000, 0x8000, 0x8000, LIB_ICON},
//WSTL_YU_OP
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8855, 0xefdf, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xe35d, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_OP_OL
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xe35d, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_YU_OP_BLUE
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8239, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_DBLUE
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8935, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_YD1
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8014, 0xfffc, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_YD2
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x821f, 0xfffc, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_Cgray
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xe35d, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_DETAIL
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xcb9f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPGBIMP
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x844b, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPGRPEW
	{C_WS_PIC_DRAW, IM_EPG_PREVIEW_T, IM_EPG_PREVIEW_L, IM_EPG_PREVIEW_R, IM_EPG_PREVIEW_B, 0xc200, INVALID_INDEX, IM_EPG_PREVIEW_L_T, IM_EPG_PREVIEW_L_B, IM_EPG_PREVIEW_R_T, IM_EPG_PREVIEW_R_B, LIB_ICON},
//WSTL_MY_EPG_TEXT
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xa25e, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_EPG_H
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xe6e1, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_HELP_ALL
	{C_WS_PIC_DRAW, IM_SHALLOW_BLUE_BAR_T_M, IM_SHALLOW_BLUE_BAR_M_L, IM_SHALLOW_BLUE_BAR_M_R, IM_SHALLOW_BLUE_BAR_B_M, 0xcb9f, INVALID_INDEX, IM_SHALLOW_BLUE_BAR_T_L, IM_SHALLOW_BLUE_BAR_B_L, IM_SHALLOW_BLUE_BAR_T_R, IM_SHALLOW_BLUE_BAR_B_R, LIB_ICON},
//WSTL_MY_PG_RECT
	{C_WS_PIC_DRAW, IM_MENU1_T, IM_MENU1_L, IM_MENU1_R, IM_MENU1_B, 0xd71e, INVALID_INDEX, IM_MENU1_LT, IM_MENU1_LB, IM_MENU1_RT, IM_MENU1_RB, LIB_ICON},
//WSTL_MY_BLUE2
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xd73e, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_BLUE1
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xf3bf, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_PG_MENU
	{C_WS_PIC_DRAW, IM_MENU2_T, IM_MENU2_L, IM_MENU2_R, IM_MENU2_B, 0xd73e, INVALID_INDEX, IM_MENU2_LT, IM_MENU2_LB, IM_MENU2_RT, IM_MENU2_RB, LIB_ICON},
//WSTL_MY_WHITE
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0xefdf, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MY_COM_TITILE_BG
	{C_WS_PIC_DRAW, IM_COM_TITLE_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BG_FOR_SIGNAL
	{C_WS_LINE_DRAW, 0xb2ff, 0xb2ff, 0xb2ff, 0xb2ff, 0xb2ff, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_YU_CA
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x5150, 0x801f, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_SHALLOW_BLUE_BAR
	{C_WS_PIC_DRAW, IM_SHALLOW_BLUE_BAR_T_M, IM_SHALLOW_BLUE_BAR_M_L, IM_SHALLOW_BLUE_BAR_M_R, IM_SHALLOW_BLUE_BAR_B_M, 0xcb9f, C_NOSHOW, IM_SHALLOW_BLUE_BAR_T_L, IM_SHALLOW_BLUE_BAR_B_L, IM_SHALLOW_BLUE_BAR_T_R, IM_SHALLOW_BLUE_BAR_B_R, LIB_ICON},
//WSTL_RCI_PIN_INPUT_SEL_SEL_BG
	{C_WS_PIC_DRAW, IM_COM_SEL_SEL_M, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0x8000, IM_COM_SEL_SEL_L2, C_NOSHOW, IM_COM_SEL_SEL_R, C_NOSHOW, LIB_ICON},
//WSTL_RCI_SHALLOW_BLUE_BAR_NOTOP
	{C_WS_PIC_DRAW, C_NOSHOW, IM_SHALLOW_BLUE_BAR_M_L, IM_SHALLOW_BLUE_BAR_M_R, IM_SHALLOW_BLUE_BAR_B_M, 0xcb9f, C_NOSHOW, C_NOSHOW, IM_SHALLOW_BLUE_BAR_B_L, C_NOSHOW, IM_SHALLOW_BLUE_BAR_B_R, LIB_ICON},
//WSTL_RCI_TXT1
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xe35d, 0x8000, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_VOLUME_BAR
	{C_WS_PIC_DRAW, IM_VULUME_BAR, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, LIB_ICON},
//WSTL_RCI_VOLUME_BG
	{C_WS_PIC_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, IM_VULUME_BAR_BG, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, LIB_ICON},
//WSTL_RCI_BLUE_BG
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8132, C_NOSHOW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_LAST_WIN_BG_NOTOP
	{C_WS_PIC_DRAW, C_NOSHOW, IM_LAST_WIN_BG_L, IM_LAST_WIN_BG_R, IM_LAST_WIN_BG_B, 0xe35d, C_NOSHOW, C_NOSHOW, IM_LAST_WIN_BG_L_B, C_NOSHOW, IM_LAST_WIN_BG_R_B, LIB_ICON},
//WSTL_MY_RE_HL
	{C_WS_PIC_DRAW, IM_EPG_PROG_ITEM_HL_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x8000, IM_EPG_PROG_ITEM_HL_L, INVALID_INDEX, IM_EPG_PROG_ITEM_HL_L, INVALID_INDEX, LIB_ICON},
//WSTL_TXT_20
	{C_WS_LINE_DRAW, 0XE35D, 0XE35D, 0XE35D, 0XE35D, 0XE35D, 0x94a5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_RCI_BLUE_FRAME
	{C_WS_PIC_DRAW, IM_BLUE_FRAME_T, IM_BLUE_FRAME_L, IM_BLUE_FRAME_R, IM_BLUE_FRAME_B, 0xaedf, 0x8000, IM_BLUE_FRAME_L_T, IM_BLUE_FRAME_L_B, IM_BLUE_FRAME_R_T, IM_BLUE_FRAME_R_B, LIB_ICON},
//WSTL_PRO_INPUT
	{C_WS_LINE_DRAW, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, 0x5150, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_EPG_TITILE_BG2
	{C_WS_PIC_DRAW, IM_EPG_MENU_TITLE_M, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_BAR_05
	{C_WS_PIC_DRAW, IM_SIGNAL_BG, IM_SIGNAL_BG, IM_SIGNAL_BG, C_NOSHOW, C_NOSHOW, C_MIXER|0xb6b9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_SIGNAL_TXT
	{C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xefdf, C_MIXER|0x8caa, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
};

#define	SIZE_WINSTYLE	sizeof(wSHStyle1)/sizeof(WINSTYLE)
